INSERT INTO inst_cat_sexo(n_id_sexo, s_sexo) VALUES
(1, 'Hombre'),
(2, 'Mujer'),
(3, 'Hombre y Mujer (Mixto)'),
(4, 'No definido');

INSERT INTO ssg_cat_tipos_acuerdos(n_id_tipo_acuerdo, s_tipo_acuerdo) VALUES
(1, 'Acuerdo de Radicación'),
(2, 'Acuerdo Diverso'),
(3, 'Acuerdo de Remisión');

INSERT INTO ssg_cat_tipo_asuntos(s_cve_tipo_asunto, s_tipo_asunto) VALUES
('JEL', 'Juicio Electoral Local'),
('JLDC', 'Juicio para la Protección de los Derechos Político-Electorales de la Ciudadanía'),
('JLI', 'Juicio para dirimir conflictos o diferencias laborales entre el IECM y sus personas servidoras públicas'),
('JLT', 'Juicio para dirimir conflictos o diferencias laborales entre el TECDMX y sus personas servidoras públicas'),
('JIAI', 'Juicio de Inconformidad Administrativa promovido(s) por personas servidoras públicas del IECM'),
('JIAT', 'Juicio de Inconformidad Administrativa promovido(s) por personas servidoras públicas del TECDMX'),
('PP', 'Procedimiento Paraprocesal'),
('PES', 'Procedimiento Especial Sancionador'),
('AG', 'Asunto General'),
('JDC FEDERAL', 'Juicio para la Protección de los Derechos Político-Electorales del Ciudadano'),
('JE FEDERAL', 'Juicio Electoral'),
('JRC FEDERAL', 'Juicio de Revisión Constitucional');

INSERT INTO ssg_cat_tipos_involucrados(n_id_tipo_involucrado, s_tipo_involucrado) VALUES
(1, 'Ciudadano'),
(2, 'Partidos Políticos'),
(3, 'Partido Político y ciudadanía '),
(4, 'Congreso de la CDMX'),
(5, 'Dirección General Jurídica de la Alcaldía Tlalpan'),
(6, 'Jefa de Gobierno de la CDMX'),
(7, 'Sistema de Aguas de la CDMX'),
(8, 'Alcaldía Coyoacán'),
(9, 'Coordinación General de la autoridad del Centro Histórico del GCDMX'),
(10, 'Unidad Técnica de Fiscalización del IECM '),
(11, 'Dirección General de Desarrollo Social de la Alcaldía Iztacalco');


INSERT INTO ssg_cat_tipos_turnados(n_id_tipo_turnado, s_tipo_turnado) VALUES
(1, 'Tipo Turnado 1'),
(2, 'Tipo Turnado 2'),
(3, 'Tipo Turnado 3');

INSERT INTO ssg_cat_tribunal(s_id_cve_tribunal, s_tribunal) VALUES
('TECDMX','Tribunal Electoral de la Ciudad de México'),
('TEDF','Tribunal Electoral del Distrito Federal');

INSERT INTO ssg_cat_via_recepcion(d_id_via_recepcion, s_via_recepcion) VALUES
(1, 'Juicio en Línea'),
(2, 'Ventanilla'),
(3, 'Correo Electrónico');

/*INSERCIONES TENPORALES*/
INSERT INTO inst_empleados(n_id_num_empleado) VALUES
(1);

INSERT INTO ssg_cat_domicilios(n_id_domicilio, s_estado, s_municipio, s_colonia, s_codigo_postal, n_id_activo) VALUES
(1, 'Ciudad de México', 'Cuauhtemoc', 'Obrera', '5300', 1);

/*END*/


INSERT INTO ssg_cat_autoridades_responsables(n_id_autoridad, s_autoridad)VALUES
(1,'Delegación Tláhuac y otro'),
(2,'Consejo General del Instituto Electoral de la Ciudad de México'),
(3,'Comisión Nacional de Justicia Partidaria del Partido Revolucionario Institucional'),
(4,'Jefe Delegacional en Tláhuac y otro'),
(5,'Jefatura Delegacional en Azcapotzalco'),
(6,'Jefe Delegacional en Tláhuac'),
(7,'Jefatura Delegacional en Tláhuac'),
(8,'Jefatura Delegacional Magdalena Contreras y otra'),
(9,'Comisiones de Encuestas y Seguimiento del Partido MORENA'),
(10,'Comité Ejecutivo Nacional del Partido Acción Nacional y otros 4'),
(11,'Comité Ejecurtivo Nacional del Partido Acción Nacional y otros 4'),
(12,'Comité Directivo Estatal del Partido Acción Nacional en la Ciudad de México y otros 4'),
(13,'Comité Ejecutivo Nacional del Partido Acción Nacional y otros 3'),
(14,'Comisión Jurisdiccional Electoral del Consejo Nacional del Partido Acción Nacional'),
(15,'Consejo Electoral de San Agustín Ohtenco en la Delegación Milpa Alta'),
(16,'Comisión Organizadora, respecto de la Consulta Ciudadana para designar al Coordinador o Coordinadora Territorial en el Pueblo de San Francisco Tlaltenco, Delegación Tláhuac'),
(17,'Dirección Distrital XXXIII del Instituto Electoral del Distrito Federal'),
(18,'Instituto Electoral del Distrito Federal (hoy Ciuad de México)'),
(19,'Jefe Delegacional en Xochimilco'),
(20,'Consejo del Pueblo de San Andrés Mixquic y otra'),
(21,'Severino Rogelio Fernández Villanueva'),
(22,'Mónica Elena Eden Wynter Gutiérrez de Velasco'),
(23,'Jefe Delegacional en Tláhuac. y otro'),
(24,'Pleno del Tribunal Electoral de la Ciudad de México'),
(25,'Dirección Distrital XVII, Cabecera de Delegación en Benito Juárez'),
(26,'Maribel Ortigoza Cru'),
(27,'Jefe Delegacional, Director General de Participación Ciudadana, Director de Gestión y Atención Vecinal, ambos en la Delegación Tláhuac'),
(28,'Jorge Javier Vergara García'),
(29,'Comisión Nacional de Honestidad y Justicia de MORENA'),
(30,'Consejo Electoral de San Francisco Tecoxpa y otro'),
(31,'Contraloría General del Instituto Electoral del Distrito Federal (hoy Ciudad de México) y otras'),
(32,'Consejo Electoral de San Francisco Tecoxpa y Jefatura Delegacional, ambas en Milpa Alta'),
(33,'Gerardo Isaac Cisneros Yescas'),
(34,'Jesús Alberto López Moreno'),
(35,'Consejo Distrital 07 del Instituto Electoral de la Ciudad de México'),
(36,'Consejo Distrital 20 del Instituto Electoral de la Ciudad de México'),
(37,'Consejo Distrital 30 del Instituto Electoral de la Ciudad de México'),
(38,'Consejo Distrital 02 del Instituto Electoral de la Ciudad de México'),
(39,'Consejo Distrital 19 del Instituto Electoral de la Ciudad de México'),
(40,'Consejo Distrital 27 del Instituto Electoral de la Ciudad de México'),
(41,'Consejo Distrital 31 del Instituto Electoral de la Ciudad de México'),
(42,'Consejo Distrital 15 del Instituto Electoral de la Ciudad de México'),
(43,'Consejo Distrital 03 del Instituto Electoral de la Ciudad de México'),
(44,'Consejo Distrital 16 del Instituto Electoral de la Ciudad de México'),
(45,'Consejo Distrital 13 del Instituto Electoral de la Ciudad de México'),
(46,'Consejo Distrital 23 del Instituto Electoral de la Ciudad de México'),
(47,'Consejo Distrital 22 del Instituto Electoral de la Ciudad de México'),
(48,'Consejo Distrital 25 del Instituto Electoral de la Ciudad de México'),
(49,'Consejo Distrital 24 del Instituto Electoral de la Ciudad de México'),
(50,'Consejo Distrital 33 del Instituto Electoral de la Ciudad de México'),
(51,'Consejo Distrital 17 del Instituto Electoral de la Ciudad de México'),
(52,'Consejo Distrital 29 del Instituto Electoral de la Ciudad de México'),
(53,'Consejo Distrital 04 del Instituto Electoral de la Ciudad de México'),
(54,'Consejo Distrital 06 del Instituto Electoral de la Ciudad de México'),
(55,'Consejo Distrital 05 del Instituto Electoral de la Ciudad de México'),
(56,'Consejo Distrital 32 del Instituto Electoral de la Ciudad de México'),
(57,'Consejo Distrital 09 del Instituto Electoral de la Ciudad de México'),
(58,'Consejo Distrital 18 del Instituto Electoral de la Ciudad de México'),
(59,'Partido Revolucionario Institucional'),
(60,'Comisión Nacional de Convenciones y Procesos Internos de Movimiento Ciudadano'),
(61,'Comité Ciudadano de la Colonia Bosque Residencial del Sur y otro'),
(62,'Comisión Estatal de Elecciones del Partido Humanista en la Ciudad de México'),
(63,'Comisión Estatal de Conciliación y Orden del Partido Humanista de la Ciudad de México'),
(64,'Consejo General del Instituto Electoral de la Ciudad de México y otro'),
(65,'Jefe Delegacional en Xochimilco y otras'),
(66,'Secretario Ejecutivo del Instituto Electoral de la Ciudad de México'),
(67,'Comisión de Justicia del Consejo Nacional del Partido Acción Nacional'),
(68,'Consejo del Pueblo de San Andrés Mixquic y otro'),
(69,'Jorge Dragan Vergara Sánchez'),
(70,'Ricardo Rodríguez Altamirano'),
(71,'Cándido Roberto Damián García'),
(72,'Pleno del Tribunal Electoral del Distrito Federal'),
(73,'Instituto Electoral del Distrito Federal (hoy Ciudad de México)'),
(74,'Liliana Sandoval Cepeda'),
(75,'Diego David Valadez Lam'),
(76,'Unidad Técnica del Centro de Formación de Desarrollo del Instituto Electoral del Distrito Federal (hoy Ciudad de México) y Dirección Ejecutiva de prerrogativas y Partidos Políticos del Instituto Nacio'),
(77,'María Elena Guevara Vizcaíno'),
(78,'Tribunal Electoral de la Ciudad de México'),
(79,'Rocío Mendoza Cruz'),
(80,'Consejo Electoral de San Francisco Tecoxpa en Milpa Alta'),
(81,'Comisión de Organización y Geoestadística Electoral del Instituto Electoral del Distrito Federal (hoy Ciudad de México)'),
(82,'Partido de la Revolución Democrática y otro'),
(83,'José Filiberto Sánchez Villanueva'),
(84,'Ricardo Ramírez Hernández'),
(85,'Comisión Organizadora para Designar al Coordinador (a) Territorial del Pueblo de Santiago Zapotitlán'),
(86,'Comision Nacional de Justicia Partidaria del Partido Revolucionario Institucional'),
(87,'Jefe Delegacional en Tláhuac y otros 3'),
(88,'Jefe Delagacional en Tláhuac'),
(89,'Jefatura Delegacional en Azcapotzalco y otra'),
(90,'Jefatura Delegacional en Iztapalapa y otras'),
(91,'Órgano Técnico Colegiado de la Delagación La Magdalena Contreras'),
(92,'Comisión Nacional de Honestidad y Justicia del Partido Político MORENA'),
(93,'Comisión provisional encargada de vigilar la oportuna conformación de los Consejos Distritales del Instituto Electoral de la Ciudad de México'),
(94,'Consejo Distrital 08 del Instituto Electoral de la Ciudad de México'),
(95,'Consejo Distrital 01 del Instituto Electoral de la Ciudad de México'),
(96,'Consejo Distrital 10 del Instituto Electoral de la Ciudad de México'),
(97,'Consejo Distrital 26 del Instituto Electoral de la Ciudad de México'),
(98,'Consejo Distrital 28 del Instituto Electoral de la Ciudad de México'),
(99,'Consejo Distrital 11 del Instituto Electoral de la Ciudad de México'),
(100,'Consejo Distrital 21 del Instituto Electoral de la Ciudad de México'),
(101,'Dirección Ejecutiva de Participación Ciudadana en la Delegación Xochimilco y otro'),
(102,'Comisión Permanente de Asociaciones Políticas del Instituto Electoral de la Ciudad de México'),
(103,'INSTITUTO ELECTORAL DEL DISTRITO FEDERAL'),
(104,'Jefe Delegacional en Xochimilco y otro'),
(105,'Comisión Nacional de Convenciones y Procesos Internos del Partido Político Movimiento Ciudadano'),
(106,'Comisión Estatal de Elecciones del Partido Humanista en la Ciudad de Mexico'),
(107,'Consejo General del Istituto Electoral de la Ciudad de México'),
(108,'Comisión Politica Permanente del Partido Revolucionario Institucional de la Ciudad de México'),
(109,'Comité Estatal del Partido de la Revolución Democrática en la Ciudad de México'),
(110,'Consejo General del Instituto Electoral del Distrito Federal'),
(111,'Jefatura Delegacional en Tlalpan'),
(112,'Comité Electoral de San Jerónimo Miacatlán, Delegación Milpa Alta y otro'),
(113,'Alma Liliana Jiménez Alvarado'),
(114,'Jefe Delegacional en Tlahuac y otro'),
(115,'Julio César Nicholson Fuentes'),
(116,'Johana Elvira Bahena Aguilar'),
(117,'Movimiento Ciudadano'),
(118,'Ruth Elizabeth Cerezo Ramírez'),
(119,'Norma Angélica Colín Navarro'),
(120,'Antonia Tapia Gómez'),
(121,'Instituto Electoral del Distrito Federal (hoy Ciudad'),
(122,'Jefa Delegacional en Tlalpan'),
(123,'Consejo General del Instituto Electoral del Distrito Federal (hoy Ciudad de México) y otra'),
(124,'Alfonso Tapia Landero'),
(125,'Instituto Electoral de la Ciudad de México'),
(126,'Comisión de Participación Ciudadana del Instituto Electoral de la Ciudad de México'),
(127,'Jefa Delegacional en Tlalpan en su carácter de Presidenta y otros 2'),
(128,'Jefe Delegacional en Tlalpan'),
(129,'Comisión Organizadora para Designar al Coordinador Territorial de Santiago Zapotitlán y otro'),
(130,'Consejo General de Instituto Electoral de la Ciudad de México'),
(131,'Comision de Justicia del Consejo Nacional del Partido Acción Nacional'),
(132,'Dirección Distrital XVII del Instituto Electoral de la Ciudad de México'),
(133,'Consejo Distrital 12 del Instituto Electoral de la Ciudad de México'),
(134,'Consejo Distrital 14 del Instituto Electoral de la Ciudad de México'),
(135,'Dirección distrital 21 del Instituto Electoral de la Ciudad de México'),
(136,'Comisión de Derechos Humanos de la Ciudad de México y otro'),
(137,'Comisión Estatal de Conciliación y otro'),
(138,'Cosejo General del Instituto Electoral de la Ciudad de México'),
(139,'Partido Humanista en el Distrito Federal (hoy Ciudad de México)'),
(140,'Dirección Distrital XVI del Instituto Electoral del Distrito Federal, (hoy Ciudad de México) y otro'),
(141,'Secretario Ejecutivo del Instituto Electoral del Distrito Federal (hoy Ciudad de México) y otro'),
(142,'Verónica Tapia Corona'),
(143,'Dirección Distrital XX del Instituto Electoral del Distrito Federal, (hoy Ciudad de México), cabecera Delegacional en Cuajimalpa de Morelos'),
(144,'David Raúl Córdova Tello'),
(145,'Ana Belén Gallegos Méndez'),
(146,'Francisco Mendieta Hernández'),
(147,'Consejo Electoral de San Bartolomé Xicomulco y otro'),
(148,'Comisión Nacional de Honestidad y Justicia de MORENA.'),
(149,'Erik Morales Mateos'),
(150,'Jefatura Delegacional en Milpa Alta'),
(151,'Consejo General del Instituto Electoral del Distrito Federal (hoy Ciudad'),
(152,'Guillermo Méndez López'),
(153,'Eduardo García Martínez'),
(154,'Asamblea Legislativa de la Ciudad de México'),
(155,'Consejo Electoral del Pueblo de Santa Ana Tlacotenco en la Delegación Milpa Alta'),
(156,'Jefatura Delegacional en Cuauhtémoc'),
(157,'Jefatura Delegacional Magdalena Contreras'),
(158,'Comisión Organizadora para designar al Coordinador(a) Territorial del Pueblo de Santiago Zapotitlán y Jefatura Delegacional ambas en Tláhuac'),
(159,'Comisión Nacional de Afiliación al Partido de la Revolución Democrática y otros 2'),
(160,'Asamblea Legislativa del Distrito Federal'),
(161,'Comisión de Conciliación y Orden del Partido Humanista de la Ciudad de México'),
(162,'Comisión Nacional de Convenciones y Procesos Internos del Partido Político Nacional Movimiento Ciudadano'),
(163,'Órgano Auxiliar de la Comisión Nacional de Procesos Internos en la Ciudad de México del Partido Revolucionario Institucional'),
(164,'Consejo General del IECM'),
(165,'Comisión Nacional de Justicia Partidaria del PRI'),
(166,'José Ramón Amieva Gálvez y otros 2'),
(167,'Congreso y Jefatura de Gobierno ambas de la Ciudad de México'),
(168,'Dirección General de Participación Ciudadana de la Alcaldía Tlalpan'),
(169,'Órgano Dictaminador de la Alcaldía Cuajimalpa Morelos'),
(170,'Dirección Distrital 26 del IECM y el Órgano Dictaminador de la Alcaldía Coyoacán'),
(171,'Titular del Órgano Interno de Control en la Alcaldía Álvaro Obregón'),
(172,'Persona titular de la Dirección General de Participación Ciudadana de la Demarcación Tlalpan'),
(173,'Junta Cívica Electoral 2023 del Pueblo Originario San Pedro Mártir'),
(174,'Comité Ejecutivo Nacional del Partido Acción Nacional y Otros'),
(175,'Comité Ejecutivo del Partido Revolucionario Institucional'),
(176,'Secretaría Administrativa, Consejo General y Junta Administrativa, todas del Instituto Electoral de la Ciudad de México'),
(177,'Dirección Distrital 30 del IECM y el Órgano Dictaminador de la Alcaldía Coyoacán'),
(178,'Santiago Taboada Cortina, Santiago Torreblanca Engell y Luis Alberto Mendoza Acevedo, en su carácter de Diputados Federales ante el Congreso de la Unión'),
(179,'Miguel Ángel Salazar Martínez, en su carácter de entonces Jefe Delegacional en Cuajimalpa'),
(180,'Dirección Distrital XIII del Instituto Electoral de la Ciudad de México'),
(181,'Comisariado Ejidal San Andrés Totoltepec y otros 6'),
(182,'Comisión Permanente de Quejas del Instituto Electoral de la Ciudad de México'),
(183,'Coalición conformada por los Partidos Políticos Acción Nacional, Revolucionario Institucional y de la Revolución Democrática'),
(184,'Dirección Distrital 19 Instituto Electoral de la Ciudad de México'),
(185,'Subdelegado del Pueblo San Pedro Mártir, Tlalpan'),
(186,'Consejo Electoral de San Antonio Tecomitl'),
(187,'Ernesto Negrete Godoy y Heriberto Galicia Muñoz, integrantes de la Autoridad Tradicional denominada Comité de Feria del Pueblo San Gregorio Atlapulco, Demarcación Xochimilco'),
(188,'Instituto Electoral de la Ciudad'),
(189,'Contraloría Interna del Instituto Electoral de la Ciudad de México'),
(190,'Junta Administrativa del Instituto Electoral de la Ciudad de México'),
(191,'Secretaría Ejecutiva del Instituto Electoral de la Ciudad de México'),
(192,'Patronato del Pueblo de San Andrés Totoltepec'),
(193,'Humberto Martínez Ramírez, Coordinador del Distrito 31 del IECM'),
(194,'Secretaría Administrativa del Instituto Electoral de la Ciudad de México'),
(195,'Alcaldía de Xochimilco'),
(196,'Jefa Delegacional y Director General Jurídico y de Gobierno, ambos de la Delegación Tlalpan'),
(197,'Jefatura Delegacional en Xochimilco'),
(198,'Junta Administrativa del Instituto Electoral de la Ciudad de México y otras'),
(199,'Jefatura Delegacional en Coyoacán'),
(200,'Autoridades Tradicionales de San Andrés Mixquic, Tláhuac'),
(201,'Consejo General del Instituto Electoral de la Ciudad de México y otra'),
(202,'Dirección Distrital 25 del Instituto Electoral de la Ciudad de México'),
(203,'Comisiones Unidas de Transparencia y Combate a la Corrupción y de Rendición de Cuentas y de Vigilancia de la Auditoría Superior, así como el Pleno, todos del Congreso de la Ciudad de México'),
(204,'Tribunal Electoral del Distrito Federal'),
(205,'Dirección Estatal Ejecutiva del Partido de la Revolución Democrática en la Ciudad de México'),
(206,'Jefatura delegacional en Álvaro Obregón'),
(207,'Junta Cívica del Pueblo de Santo Tomas Ajusco'),
(208,'Secretaria Administrativa del Instituto Electoral de la Ciudad de México'),
(209,'Secretaría Administrativa del IECM'),
(210,'Dirección Distrital 30 del Instituto Electoral de la Ciudad de México'),
(211,'Secretaría de Organización del Comité Ejecutivo Nacional de Morena y otros'),
(212,'Contraloría Interna del Tribunal Electoral de la Ciudad de México.'),
(213,'Dirección Distrital 14 del Instituto Electoral de la Ciudad de México'),
(214,'Santiago Taboada Cortina y otros en sus calidades de candidatos a la Alcaldía de Benito Juárez'),
(215,'Alcaldía Xochimilco'),
(216,'Director General de Jurídico y Gobierno de la Delegación Xochimilco'),
(217,'Secretaría Ejecutiva del Instituto Electoral de la Ciudad de México.'),
(218,'Alcaldía Coyoacán'),
(219,'Delegación Cuauhtémoc'),
(220,'Jefa de Gobierno y Congreso ambos de la Ciudad de México'),
(221,'Congreso de la Ciudad de México'),
(222,'Contralor General hoy Contralor Interno del Instituto Electoral de la Ciudad de México'),
(223,'Jefe Delegacional de Tlalpan, Ciudad de México.'),
(224,'Mikel Andoni Arriola Peñalosa, candidato a Jefe de Gobierno de la Ciudad de México, postulado por el Partido Revolucionario Institucional y otros'),
(225,'Alcaldía Cuauhtémoc'),
(226,'Concejo de la Alcaldía de Tlalpan, Ciudad de México'),
(227,'Congreso de la Ciudad de México II Legislatura'),
(228,'Dirección Distrital 9 del IECM'),
(229,'Dirección Distrital 2 del Instituto Electoral de la Ciudad de México'),
(230,'Unidad Técnica de Asuntos Jurídicos del Instituto Electoral de la Ciudad de México'),
(231,'Leticia Bravo Contreras, en su carácter de Jefa de Unidad Departamental “C” en la Delegación Gustavo A. Madero y otros'),
(232,'Consejo Electoral de Santa Ana Tlacotenco, Milpa Alta'),
(233,'Dirección Distrital 16 Instituto Electoral de la Ciudad de México'),
(234,'Miguel Ángel Reyes Guerrero y otros'),
(235,'Alcaldía Álvaro Obregón'),
(236,'Mikel Andoni Arriola Peñalosa, en su calidad de candidato a la Jefatura de Gobierno de la Ciudad de México, postulado por el Partido Revolucionario Institucional'),
(237,'Jefatura Delegacional en Coyoacán y Comité Ciudadano en la Colonia CTM V Culhuacán'),
(238,'Ciudadano Fadlala Akabani Hneide, en su calidad de candidato a la Alcaldía en Benito Juárez, postulado por la candidatura común conformada por los partidos Morena, del Trabajo y Encuentro Social'),
(239,'Agustín Ontiveros Pineda Garza y José Edwin Pérez Fonseca, candidatos a Concejales, postulados por la coalición “Por la CDMX al Frente”, así como la coalición “Por la CDMX al Frente'),
(240,'Presidente del Patronato Santiago Apóstol del Pueblo Santiago Tulyehualco, Xochimilco'),
(241,'IECM'),
(242,'Junta Cívica del Pueblo originario de San Pedro Mártir'),
(243,'Delegación Azcapotzalco'),
(244,'Víctor Hugo Romo de Vivar Guerra, candidato a la Alcaldía en Miguel Hidalgo, postulado por la candidatura común “Juntos Haremos Historia” y el Partido Morena en la Ciudad de México'),
(245,'Karen Quiroga Anguiano, en su carácter de candidata a la Alcaldía en Iztapalapa, postulada por la coalición “Por la CDMX al Frente” y otras'),
(246,'Manuel Negrete Arias, en su calidad de Candidato a la Alcaldía en Coyoacán, postulado por la coalición “Por la CDMX al Frente” y la Coalición “Por la CDMX al Frente'),
(247,'Patricia Paola Mendoza Franco Mendoza, en su carácter de Directora Ejecutiva de Innovación y Proyectos de la Central de Abastos.'),
(248,'Alcaldía Álvaro Obregón.'),
(249,'Sistema de Aguas de la Ciudad de México'),
(250,'Secretaría Administrativa del Instituto Electoral de la Ciudad'),
(251,'Dione Anguiano Flores, en su calidad de Jefa Delegacional en Iztapalapa y otros'),
(252,'Jefe Delegacional de Iztacalco y otros'),
(253,'Dirección Distrital 26 del Instituto Electoral de la Ciudad de México'),
(254,'Margarita María Martínez Fisher, en su calidad de candidata a la Alcaldía en Miguel Hidalgo, postulada por la coalición “Por la CDMX al Frente”; así como la coalición “Por la CDMX al Frente'),
(255,'Alcaldía Benito Juárez'),
(256,'Comisión Provisional para vigilar la oportuna conformación de los Consejos Distritales del Instituto Electoral de la Ciudad de México'),
(257,'Unidad Técnica del Centro de Formación y Desarrollo y la Comisión Provisional para vigilar la oportuna conformación de los Consejos Distritales, ambas del Instituto Electoral de la Ciudad de México'),
(258,'Coalición “Por la CDMX al Frente” y Otros'),
(259,'Autoridades Tradicionales del Pueblo Originario de San Pedro Tláhuac'),
(260,'Contralor Interno del Instituto Electoral de la Ciudad de México'),
(261,'Patricia Elena Aceves Pastrana y otras personas'),
(262,'Víctor Hugo Romo De Vivar y Hegel Cortés Miranda, Alcalde y Director General de Gobierno y Asuntos Jurídicos ambos en la Alcaldía Miguel Hidalgo'),
(263,'Secretaria Administrativa del IECM'),
(264,'Secretaría de Administración del Instituto Electoral de la Ciudad de México'),
(265,'Concejo de Gobierno de San Luis Tlaxialtemalco'),
(266,'Alcaldía Xochimilco e Instituto Electoral de la Ciudad de México'),
(267,'Alcaldía de Xochimilco e Instituto Electoral de la Ciudad de México'),
(268,'Personas ex integrantes del Comité Pro-Panteón del pueblo de San Gregorio Atlapulco'),
(269,'Patricia González Guzmán, Presidenta del Comité Pro-Panteón del Pueblo de San Gregorio Atlapulco, reestructurado 2021-2024'),
(270,'Patricia González Guzmán, quien se ostenta como Presidenta del Comité Pro-Panteón del Pueblo de San Gregorio Atlapulco y otras personas'),
(271,'Órgano Dictaminador de la Alcaldía La Magdalena Contreras'),
(272,'Congreso y Jefatura de Gobierno, ambas de la Ciudad de México'),
(273,'Consejo Electoral del Pueblo San Salvador Cuauhtenco, Milpa Alta'),
(274,'Secretaría Técnica de la Comisión Provisional para Vigilar la Oportuna Conformación de los Consejos Distritales'),
(275,'Comisión de Justicia del Partido Acción Nacional'),
(276,'Raúl Paredes Peña, en su carácter de Concejal en la Demarcación Territorial Miguel Hidalgo'),
(277,'Dirección Distrital 25 del IECM'),
(278,'Comisión Nacional de Honorable Justicia de MORENA'),
(279,'Comision Provisional para Vigilar la Conformación de los Consejos Distritales'),
(280,'Dirección Distrital 8 del IECM y Alcaldía Tláhuac'),
(281,'Alcaldia Tlalpan'),
(282,'Ángel Flores Patricio y otra persona trabajadores de Aculco en la Demarcación Territorial Iztapalapa'),
(283,'Maura Margarita Cruz Martínez y otras personas'),
(284,'Junta y Secretaria Administratibas ambas del Instituto Electoral de la Ciudad de México'),
(285,'Junta Cívica y Comisariado Ejidal, ambos del Pueblo San Lorenzo Huipulco'),
(286,'Dirección Distrital 2 del IECM'),
(287,'Alcaldía Coyoacán y su Dirección de Participación Ciudadana'),
(288,'Contraloría Interna del Tribunal Electoral de la Ciudad de México'),
(289,'Junta Cívica del Pueblo de San Miguel Topilejo y la Alcaldía Tlalpan'),
(290,'Comisión Redactora del Pueblo de San Pedro Mártir'),
(291,'Dirección Ejecutiva de Asociaciones Políticas del Instituto Electoral de la Ciudad de México'),
(292,'Secretarías Ejecutiva y Administrativa, ambas del Instituto Electoral de la Ciudad de México'),
(293,'Dirección Distrital 12 del IECM'),
(294,'Comisión Organizadora de la Elección de la persona Coordinadora Territorial del Pueblo de San Nicolás Tetelco, Demarcación Tláhuac'),
(295,'Alejandro Negrete integrante del Concejo del Pueblo de San Luis Tlaxialtemalco'),
(296,'Dirección Ejecutiva de Regulación de Sistemas de Movilidad Urbana Sustentable de la Secretaría de Movilidad de la Ciudad de México'),
(297,'Órgano de Justicia Intrapartidaria del Partido de la Revolución Democrática'),
(298,'Unidad Técnica de Asuntos Jurídicos y la Secretaría Técnica de la Comisión Permanente de Seguimiento al Servicio Profesional Electoral Nacional del Instituto Electoral de la Ciudad de México'),
(299,'Pedro Pablo de Antuñano Padilla, Presidente del Consejo Estatal del Partido Redes Sociales Progresistas'),
(300,'Salomón Chertorivski Woldenberg, en su calidad de Diputado Federal y otro'),
(301,'Consejo General del Instituto Electoral de la Ciudad de México y la Secretaría Técnica de la Comisión Provisional encargada de Vigilar la Oportuna Conformación de los Consejos Distritales.'),
(302,'Dirección de Participación Ciudadana de la Alcaldía Xochimilco'),
(303,'Directora Ejecutiva de Asociaciones Políticas del Instituto Electoral de la Ciudad de México'),
(304,'Comisión de Quejas del Instituto Electoral de la Ciudad de México'),
(305,'Dirección General de Participación Ciudadana de la Alcaldía Coyoacán y otras'),
(306,'Rosalía Martha Elvira López Herrera, Concejala en la Alcaldía Azcapotzalco'),
(307,'María del Carmen Pacheco Gamiño, persona candidata a la Alcaldía Gustavo A. Madero, Postulada por los Partidos Acción Nacional'),
(308,'Nora Arias Contreras, en su calidad de dirigente estatal del Partido de la Revolución Democrática, el Partido de la Revolución Democrática y quienes resulten responsables'),
(309,'Dirección Distrital 29 del IECM'),
(310,'Comisión de Festejos de San Jerónimo Lídice'),
(311,'Alcaldía Tlahuac'),
(312,'María Alejandra Barrales Magdaleno, otrora candidata a Jefa de Gobierno de la Ciudad de México, postulada por la coalición “Por la CDMX al Frente” y Otro'),
(313,'Dirección Distrital 16 del IECM'),
(314,'Areli Camacho Evangelista y otras personas todos integrantes de la Junta Cívica del Pueblo de Santo Tomas Ajusco 2022-2025'),
(315,'Secretaría de Pueblos y Barrios Originarios de la Ciudad de México'),
(316,'Comité Ejecutivo Nacional del Partido Acción Nacional'),
(317,'Dirección Distrital 17 del Instituto Electoral de la Ciudad de México'),
(318,'Secretaría Técnica de la Comisión Provisional encargada de Vigilar la Oportuna Conformación de los Consejos Distritales'),
(319,'Secretaría Ejecutiva del Instituto Electoral de la Ciudad de México y otra y otro'),
(320,'Christian de Jesús Fuentes y otras personas'),
(321,'Comisión Nacional de Afiliación del Partido Acción Nacional'),
(322,'Comisión Redactora Electoral del Pueblo de San Pedro Mártir, Alcaldía Tlalpan y el Instituto Electoral de la Ciudad de México'),
(323,'Secretetaría Administrativa del Instituto Electoral de la Ciudad de México'),
(324,'Comisión de Igualdad de Género del Congreso de la Ciudad de México'),
(325,'Consejo Electoral 2022 de San Salvador Cuauhtenco, Demarcación Territorial Milpa Alta'),
(326,'Dirección de Participación Ciudadana de la Alcaldía Xochimilco.'),
(327,'Secretaría del Medio Ambiente de la Ciudad de México'),
(328,'Comisión Organizadora Electoral en la Ciudad de México del Partido Acción Nacional'),
(329,'Sandra Xantal Cuevas Nieves y los Partidos Políticos Acción Nacional, Revolucionario Institucional y de la Revolución Democrática'),
(330,'Armando Tonatiuh Hernández Cuazitl en su calidad de persona candidata a Diputación Migrante, postulado por el Partido Redes Sociales Progresistas, así como dicho instituto político'),
(331,'María de los Dolores Padierna Luna y los Partidos Políticos Morena y del Trabajo'),
(332,'Junta Cívica del Pueblo Originario de Chimalcoyoc, Tlalpan'),
(333,'Junta Cívica del Pueblo de Chimalcoyoc, Tlalpan'),
(334,'Comité Directivo del Partido Revolucionario Institucional en la Ciudad de México'),
(335,'Dirección Distrital 19 del IECM'),
(336,'Dirección Distrital 8 del IECM y la Alcaldía de Tláhuac'),
(337,'Alcaldía Coyoacán y otras personas'),
(338,'Partido Morena'),
(339,'Comisión Organizadora de la Elección para la Coordinación del Pueblo de San Andrés Mixquic'),
(340,'José Giovani Gutiérrez Aguilar otrora candidato a la Alcaldía Coyoacán, postulado por la candidatura común “Va por México”'),
(341,'Citlalli Hernández Mora, Secretaria General del Comité Ejecutivo Nacional del Partido Morena'),
(342,'Consejo Estatal y Dirección Estatal Ejecutiva, ambas del Partido de la Revolución Democrática'),
(343,'Módulo del Instituto Nacional Electoral en el Distrito 12'),
(344,'Secretaría Técnica de la Comisión de Seguimiento al Servicio Profesional Electoral Nacional del IECM'),
(345,'Clara Marina Brugada Molina, en su calidad de Alcaldesa de Iztapalapa y otra persona'),
(346,'Sebastián Ramírez Mendoza, Presidente del Comité Ejecutivo Estatal de MORENA en la Ciudad de México y otras personas y otro'),
(347,'Direcció General de Participación Ciudadana de la Alcaldía Xochimilco'),
(348,'Presidencia de la Mesa Directiva del Congreso de la Ciudad de México'),
(349,'Comité Ejecutivo Nacional, Comisión Nacional de Elecciones y comisión Nacional de Encuestas, todos del Partido Morena'),
(350,'Laura Ballesteros Mancilla, militante del Partido Acción Nacional y otros'),
(351,'Contraloría Interna del TECDMX'),
(352,'Alcaldía Azcapotzalco y la Subdirección de Vinculación de Presupuesto Participativo de dicho Órgano Político Administrativo'),
(353,'Alcaldía Gustavo A. Madero'),
(354,'América Alejandra Rangel Lorenzana, persona candidata a la Diputación del Congreso de la Ciudad de México por el Partido Acción Nacional'),
(355,'Alcaldía Iztapalapa'),
(356,'Dirección Distrital 12 del Instituto Electoral de la Ciudad de México'),
(357,'Órgano Dictaminador de la Alcaldía de Tlalpan'),
(358,'Concejo de la Alcaldía Venustiano Carranza'),
(359,'Alcaldía Azcapotzalco y Subdirección de Vinculación Ciudadana y Seguimiento al Presupuesto Participativo de dicho Órgano Político Administrativo'),
(360,'Sandra Xantall Cuevas Nieves, Titular de la Alcaldía Cuauhtémoc'),
(361,'Dirección Distrital 19 del Instituto Electoral de la Ciudad de México'),
(362,'Jesús Sesma Suárez, Diputado del Congreso de la Ciudad de México'),
(363,'Organo Dictaminador de la Alcaldía Coyoacán'),
(364,'Alcaldía Coyoacán y la Dirección General de Participación Ciudadana de dicho Órgano Político Administrativo'),
(365,'Tribunal Electoral de la Ciudad de Méxcio'),
(366,'Dirección Distrital 30 del IECM y Órgano Dictaminador de la Alcaldía de Coyoacán'),
(367,'Dirección Ejecutiva de Asociaciones Políticas y Consejero Presidente, ambos del Instituto Electoral de la Ciudad de México y otras'),
(368,'Órgano Dictaminador de la Alcaldía Miguel Hidalgo'),
(369,'Comisión Organizadora del Pueblo de San Pedro Tláhuac'),
(370,'Nitzia Lucero Rosas Chávez, en su calidad de Concejala de la Alcaldía Xochimilco'),
(371,'Comité Ejecutivo Nacional y Comisión Nacional de Elecciones, ambas del Partido Morena'),
(372,'Unidad Técnica del Centro de Formación y Desarrollo del IECM'),
(373,'José Octavio Rivero Villaseñor, en su calidad de alcaldía de Milpa Alta'),
(374,'Órgano Dictaminador de la Alcaldía Coyoacán'),
(375,'Órgano Dictaminador de la Alcaldía Azcapotzalco'),
(376,'X Consejo Estatal y Dirección Estatal Ejecutiva, ambas del Partido de la Revolución Democrática'),
(377,'Javier Antonio Castro Chávez'),
(378,'Patronato del Panteón de San Jerónimo Aculco Lídice, La Magdalena Contreras'),
(379,'Autoridades Tradicionales del Pueblo de Santiago Zapotitlán Demarcación Territorial Tláhuac'),
(380,'Partido de la Revolución Democrática'),
(381,'Héctor Hugo Hernández Rodríguez otrora persona candidata a Alcalde en Tlalpan postulado por el Partido Movimiento Ciudadano, así como el Partido Político'),
(382,'Nazario Norberto Sánchez, Diputado del Congreso de la Ciudad de México'),
(383,'Rodrigo Saval Pasquel y el Partido Movimiento Ciudadano'),
(384,'Órgano Dictaminador de la Alcaldía Xochimilco'),
(385,'Mauricio Tabe Echartea, Diputado del Congreso de la Ciudad de México'),
(386,'Rocío Barrera Badillo en su calidad de persona candidata a Alcaldesa en Venustiano Carranza postulado por la candidatura común “Va por la Ciudad de México”'),
(387,'Consejo General del Instituto Electoral de la Ciudad de México y Comisión Nacional de Honestidad y Justicia del Partido Morena'),
(388,'Carlos Esteban Jiménez Martínez'),
(389,'Comisión Permanente de Participación Ciudadana y Capacitación del Instituto Electoral de la Ciudad de México'),
(390,'Órgano Dictaminador de la Alcaldía Tláhuac'),
(391,'Comité Ejecutivo Nacional Partido Morena'),
(392,'Órgano Dictaminador de la Alcaldía Cuajimalpa de Morelos'),
(393,'José Martín Padilla Sánchez, Diputado del Congreso de la Ciudad de México'),
(394,'Dirección Distrital 19 del Instituto Electoral y Contraloría General ambos de la Ciudad de México'),
(395,'Consejo General y Dirección Ejecutiva de Asociaciones Políticas, ambos del Instituto Electoral de la Ciudad de México'),
(396,'Comisión de Participación Ciudadana de la Unidad Territorial Bosque Residencial del Sur, Demarcación Xochimilco'),
(397,'Junta Cívica del Pueblo Originario de San Lorenzo Huipulco'),
(398,'Órgano Dictaminador de la Alcaldía Gustavo A. Madero'),
(399,'Dirección Distrital 23 del Instituto Electoral de la Ciudad de México'),
(400,'Alcaldía Tlalpan'),
(401,'Comité Directivo Regional del Partido Acción Nacional de la Ciudad de México'),
(402,'Pedro Haces Barba, en su calidad de Senador Suplente de la República'),
(403,'Rafael Calderón Jiménez, en su calidad de Secretario de Asuntos Electorales del Partido Acción Nacional y el Partido Acción Nacional'),
(404,'Paula Adriana Soto Maldonado, Partido Morena y del Trabajo'),
(405,'Víctor Hugo Romo de Vivar Guerra, en su calidad de persona aspirante a la reelección para la Alcaldía Miguel Hidalgo por Partido MORENA y otra persona'),
(406,'Órgano Dictaminador de la Alcaldía Milpa Alta'),
(407,'Alcaldía Milpa Alta'),
(408,'Partido MORENA y el presidente del Comité Ejecutivo Estatal de MORENA en la Ciudad de México'),
(409,'Rosa María Azucena Narváez Hernández, Concejala de la Alcaldía Azcapotzalco y los Partidos Políticos MORENA y del Trabajo'),
(410,'Nazario Norberto Sánchez, otrora candidato a Diputado'),
(411,'Junta Administrativa y Unidad Técnica del Centro de Formación y Desarrollo del IECM'),
(412,'Consejo Electoral de San Antonio Tecómitl, Milpa Alta'),
(413,'Secretario Administrativo del Instituto Electoral de la Ciudad de México'),
(414,'Adrián Rubalcava Suárez, Alcalde en Cuajimalpa de Morelos'),
(415,'Evaristo Roberto Candia Ortega, Diputado del Congreso de la Ciudad de México'),
(416,'Comisión Nacional de Honestidad y Justicia del Partido MORENA'),
(417,'Luis Ángel Xariel Espinosa Cházaro, es su calidad de Diputado Federal'),
(418,'Comité Ejecutivo Nacional de Morena y otros'),
(419,'Clara Marina Brugada Molina, otrora Titular de la Alcaldía Iztapalapa y quienes resulten responsables'),
(420,'Junta Administrativa, Unidad Técnica del Centro de Formación y Desarrollo y Unidad Técnica de Servicios Informáticos del Instituto Electoral de la Ciudad de México'),
(421,'Consejo General y la Secretaria Admnistrativa del Instituto Electoral de la Ciudad de México'),
(422,'Mauricio Tabe Echartea, Diputado del Congreso de la Ciudad de México.'),
(423,'Rocío Barrera Badillo, en calidad de Diputada del Congreso de la Unión.'),
(424,'Comisión Permanente de Participación Ciudadana y Capacitación'),
(425,'Adela Piña Bernal, Diputada del Congreso de la Unión'),
(426,'Comisión Nacional de Elecciones del Partido Morena'),
(427,'Dirección Distrital 17 del IECM'),
(428,'José Ricardo Fuentes Gómez, Diputado del Congreso de la Ciudad de México'),
(429,'Junta Administrativa del IECM'),
(430,'Carol Berenice Arriaga García otras personas'),
(431,'Órgano Dictaminador de la Alcaldía Iztapalapa'),
(432,'Sala Regional de la Ciudad de México'),
(433,'Alcaldía Azcapotzalco'),
(434,'Instituto Electoral de la Ciudad de México y Partido Morena'),
(435,'Mesa Directiva y Junta de Coordinación Política, ambas del Congreso de la Ciudad de México'),
(436,'Dirección Distrital 23 del IECM'),
(437,'Comité del Órgano Auxiliar de la Comisión Nacional de Procesos Internos del Partido Revolucionario Institucional'),
(438,'Tribunal de Justicia Administrativa de la Cidad de México'),
(439,'Tribunal de Justicia Administrativa de la Ciudad de México'),
(440,'Secretaría de Pueblos y Barrios Originarios y Comunidades Indígenas Residentes'),
(441,'Lizette Clavel Sánchez, Diputada del Congreso de la Ciudad de México'),
(442,'Néstor Núñez López Alcalde en Cuauhtémoc y otras personas'),
(443,'Evelin Parra Álvarez diputada del Congreso de la Ciudad de México'),
(444,'Partido MORENA en la Ciudad de México'),
(445,'Héctor Hugo Hernández Rodríguez, en su calidad de candidato a la Alcaldía de Tlalpan postulado por el Partido Movimiento Ciudadano'),
(446,'Secretaría Administrativa Instituto Electoral de la Ciudad de México'),
(447,'Lía Limón García, persona candidata a Alcaldesa en Álvaro Obregón, postulada por los Partidos Acción Nacional, Revolucionario Institucional y de la Revolución Democrática, y otras personas'),
(448,'Diego Orlando Garrido López, Diputado del Congreso de la Ciudad de México'),
(449,'Raúl Paredes Peña, en su Carácter de Concejal en la Alcaldía Miguel Hidalgo'),
(450,'Comisión Nacional de Elecciones del Partido MORENA y otros 2'),
(451,'Raúl Armando Quintero Martínez, otrora persona candidata a la Alcaldía Iztacalco y los Partidos Morena y del Trabajo'),
(452,'Comisión Nacional de Elecciones del Partido MORENA y otro'),
(453,'Subdelegado del Pueblo Santo Tomás Ajusco, Demarcación Tlalpan'),
(454,'Secretarío Administrativo y Secretario de la Junta Administrativa del Instituto Electoral de la Ciudad de México'),
(455,'Comisión de Participación Comunitaria, Unidad Territorial Esperanza'),
(456,'Jorge Emilio Sánchez Cordero Grossman y otra persona'),
(457,'Jorge Alvarado Galicia y otras personas'),
(458,'Rigoberto Ávila Ordóñez, titular de la Alcaldía de Coyoacán y otras personas'),
(459,'Instituto Nacional Electoral'),
(460,'Roberto Candia Ortega, Diputado del Congreso de la Ciudad de México'),
(461,'Víctor Hugo Romo de Vivar Guerra, en su calidad de persona candidata a la Alcaldía en Miguel Hidalgo'),
(462,'Francisco Javier Saldívar Camacho, Diputado del Congreso de la Ciudad de México'),
(463,'Dirección Distrital 33 del IECM'),
(464,'Cristian Vega Miranda, otrora persona candidata a Concejal, y otras personas'),
(465,'Dirección Distrital 06 del Instituto Electoral de la Ciudad de México'),
(466,'Francisco Chiguil Figueroa y otras personas'),
(467,'Dirección Distrital 1 del IECM'),
(468,'Sala Regional CDMX'),
(469,'Comité Directivo Regional del Partido Acción Nacional'),
(470,'Dirección Distrital 6 del Instituto Electoral de la Ciudad de México'),
(471,'Comisión Nacional de Elecciones y Comité Ejecutivo Nacional, ambas del Partido Morena'),
(472,'Teresa Ortega Rico, Concejala en la Alcaldía Iztapalapa y otras personas'),
(473,'Juan José Sánchez González, Director General de Bienestar Social de la Alcaldía la Magdalena Contreras'),
(474,'Subdirección de Concertación Social de la Alcaldía Coyoacán'),
(475,'Órgano Dictaminador de la Alcaldía Iztacalco'),
(476,'Consejo Electoral de San Antonio Tecómitl 2020, Milpa Alta'),
(477,'Órgano Dictaminador de la Alcaldía Álvaro Obregón'),
(478,'Raúl Paredes Peña, Concejal en la Alcaldía Miguel Hidalgo'),
(479,'Carlos Hernández Mirón, Diputado del Congreso de la Ciudad de México.'),
(480,'Órgano Dictaminador de la Alcaldía Benito Juárez'),
(481,'Comisión de Justicia del Consejo Nacional Partido Acción Nacional'),
(482,'Dirección Distrital 18 del IECM'),
(483,'Consejos Generales del Instituto Electoral de la Ciudad de México e Instituto Nacional Electoral'),
(484,'Dirección Distrital 6 del IECM'),
(485,'Dirección Distrital 15 del IECM'),
(486,'Tribunal Electoral de la Ciudad de México.'),
(487,'Dirección Distrital 20 del Instituto Electoral de la Ciudad de México'),
(488,'Felipe Nájera Arreola y el Partido Morena'),
(489,'Secretaría de Pueblos y Barrios Originarios y Comunidades Indígenas Residentes de la Ciudad de México e Instituto Electoral de la Ciudad de México'),
(490,'Consejo Nacional del Partido Morena y otros 2'),
(491,'Coordinación Jurídica del Comité Ejecutivo Nacional del Partido Morena'),
(492,'Nazario Norberto Sánchez, Diputado integrante del Grupo Parlamentario del Partido MORENA'),
(493,'Órgano Dictaminador de la Alcaldía Cuauhtémoc'),
(494,'Dirección Nacional Ejecutiva del Partido de la Revolución Democrática y otro'),
(495,'Teresa Ortega Rico, Concejala de la Alcaldía Iztapalapa y los Partidos MORENA y del Trabajo'),
(496,'Néstor Núñez López, Alcalde de la Demarcación Territorial Cuauhtémoc y otras personas'),
(497,'Dirección Ejecutiva de Asociaciones Políticas y Fiscalización del IECM'),
(498,'Comisión Nacional de Elecciones del Partido MORENA y otros 3'),
(499,'Comisión Nacional de Justicia Intrapartidaria de Movimiento Ciudadano'),
(500,'Secretaría de Procesos Electorales Estatal y la Comisión Nacional de Procesos Internos, ambas del Partido Verde Ecologista de México en esta Ciudad'),
(501,'Frente Social Causa Altépetl Texopanco'),
(502,'Dirección Distrital 01 del Instituto Electoral de la Ciudad de México'),
(503,'Director de Participación Ciudadana de la Alcaldía Coyoacán y otro'),
(504,'Alcaldía Iztapalapa, Dirección General de Obras y Desarrollo Urbano, Dirección de Participación Ciudadana, ambas de dicha Alcaldía.'),
(505,'Alcaldía Tláhuac'),
(506,'Secretaría de Desarrollo Urbano y Vivienda de la Ciudad de México'),
(507,'Partido Movimiento Ciudadano en la Ciudad de México'),
(508,'Santiago Taboada Cortina, en su calidad de Titular de la Alcaldía Benito Juárez'),
(509,'Pablo Trejo Pérez, Director General de Administración de la Alcaldía Gustavo A. Madero'),
(510,'Dirección Distrital 33 del Instituto Electoral de la Ciudad de México'),
(511,'Rigoberto Salgado Vázquez, Diputado del Congreso de la Ciudad de México.'),
(512,'Flor Ivone Morales Miranda, Directora General de Asuntos Metropolitanos y Enlace Gubernamental de la Secretaría de Gobierno de la Ciudad de México'),
(513,'Unidad de Transparencia de la Secretaría Ejecutiva del Instituto Electoral de la Ciudad de México'),
(514,'Consejo Electoral de San Lorenzo Tlacoyucan, Milpa Alta'),
(515,'Alcaldía Alvaro Obregón'),
(516,'Rodrigo Menéndez Roldán'),
(517,'Comisión de Elecciones del Partido Morena'),
(518,'Consejo General Instituto Electoral de la Ciudad de México'),
(519,'Dirección Distrital 26 del IECM'),
(520,'Víctor Hugo Romo de Vivar Guerra, Alcalde en Miguel Hidalgo'),
(521,'Carlos Alonso Castillo Pérez, Diputado del Congreso de la Ciudad de México'),
(522,'Dirección Distrital 14 del IECM'),
(523,'Dirección Distrital 20 del IECM'),
(524,'Concejo de Gobierno del Pueblo de San Andrés Totoltepec y Alcaldía Tlalpan'),
(525,'Comisión de Festejos del Pueblo de San Jerónimo Lidice'),
(526,'Partidos de la Revolución Democrática, Acción Nacional y otros 2'),
(527,'Víctor Hugo Romo de Vivar Guerra Alcalde en Miguel Hidalgo'),
(528,'Jefatura de Gobierno de la CDMX'),
(529,'Lía Limón García, Alcaldesa de Álvaro Obregón'),
(530,'Héctor Saúl Téllez Hernández y otras personas'),
(531,'Juan Manuel Ballesteros López y otras personas'),
(532,'Laura Carrillo “N” y/o quien resulte responsable'),
(533,'Lía Limón García, en su calidad de Alcaldesa en Álvaro Obregón'),
(534,'María de los Dolores Padierna Luna, Diputada del Congreso de la Unión'),
(535,'Dirección Distrital 13 del IECM'),
(536,'Dirección Distrital 28 del IECM'),
(537,'Roberto Candía Ortega, Diputado Suplente del Congreso de la Ciudad de México y otras personas'),
(538,'Dirección Distrital 11 del IECM'),
(539,'Secretaría de Administración y Finanzas de la Ciudad de México'),
(540,'Comisión Organizadora de la Elección de la Coordinadora o Coordinador Territorial en el Pueblo de San Francisco Tlaltenco y la Alcaldía Tláhuac'),
(541,'Eduardo Santillán Pérez, Diputado del Congreso de la Ciudad de México y otro'),
(542,'Lucía Flores Olivo, Diputada del Congreso de la Unión'),
(543,'Presidente del Partido Verde Ecologista de México en la Ciudad de México'),
(544,'Santiago Taboada Cortina, Alcalde de Benito Juárez'),
(545,'Dirección Distrital 33 Instituto Electoral de la Ciudad de México'),
(546,'Presidenta del Consejo General del Pueblo San Salvador Cuauhtenco, Milpa Alta'),
(547,'Dirección General de la Comisión de Recursos Naturales y Desarrollo Rural de la Secretaría del Medio Ambiente de la Ciudad de México'),
(548,'José Ulises Cedillo Rangel'),
(549,'Paula Adriana Soto Maldonado, otrora persona candidata a la Alcaldía Benito Juárez, postulada por la candidatura en común “Juntos hacemos Historia Ciudad de México”.'),
(550,'Araceli Berenice Hernández Calderón otrora persona candidata a la Alcaldía Tláhuac'),
(551,'Comisión Nacional de Honestidad y Justicia, Comisión Nacional de Elecciones y otro'),
(552,'Persona Subdelegada del Pueblo Santo Tomás Ajusco, Demarcación Tlalpan'),
(553,'José Javier Gómez Hernández y la Alcaldía Cuauhtémoc'),
(554,'Partido Acción Nacional y otras personas'),
(555,'Dirección Distrital 21 del IECM'),
(556,'Dirección Distrital 30 del IECM'),
(557,'José de Jesús Suárez García y otros 2'),
(558,'Dirección Distrital 3 del IECM'),
(559,'Organo Dictaminador de la Alcaldía Tlalpan'),
(560,'Dirección Distrital 4 del IECM'),
(561,'Comisión Redactora electa en funciones de Junta Cívica Electoral del Pueblo de San Pedro Mártir'),
(562,'Alicia Ana Lilia Robles Acevedo, otrora persona candidata a la Alcaldía Milpa Alta'),
(563,'Mauricio Tabe Echartea, persona candidata a la titularidad de la Alcaldía en Miguel Hidalgo'),
(564,'Comisiones Unidas de Transparencia y Combate a la Corrupción y de Rendición de Cuentas y de Vigilancia de la Auditoría Superior y otro'),
(565,'María del Rosario Morales Ramos'),
(566,'Francisco Javier Saldívar Camacho, Diputado del Congreso de la Unión'),
(567,'Jorge Emilio Sánchez Cordero Grossman'),
(568,'Jorge Emilio Sánchez Cordero Grossman y otro'),
(569,'Paula Adriana Soto Maldonado, Diputada del Congreso de la Ciudad de México y otra persona'),
(570,'Ana Cristina Hernández Trejo, Diputada del Congreso de la Ciudad de México'),
(571,'Medios de Comunicación Electrónica, el Big Data MX, El Financiero MX y El Universal MX'),
(572,'Jorge Emilio Sánchez Cordero Grossmann'),
(573,'Consejo General del Pueblo San Salvador Cuauhtenco, Milpa Alta'),
(574,'Raúl Armando Quintero Martínez, otrora persona candidata a la Alcaldía Iztacalco'),
(575,'Adolfo Llubere Sevilla, persona candidata a la Alcaldía Tlalpan, postulada por el Partido Fuerza por México y dicho Instituto Político'),
(576,'Comisión Nacional de Justicia y Ética Partidaria del Partido Político Redes Sociales Progresistas'),
(577,'“Diario Basta Redacción Grupo Cantón” y “Votia Sistemas de Información”'),
(578,'Olivia Margarita González Patiño integrante del Comité de Vigilancia para el Ejercicio Fiscal 2021 de la Unidad Territorial Romero de Terreros, Coyoacán'),
(579,'Dirección Distrital 11 del Instituto Electoral de la Ciudad de México y otra persona'),
(580,'Comisión Sociocultural y Deportiva del Pueblo Originario de San Pedro Mártir, Tlalpan'),
(581,'Dirección Distritial 22 del IECM'),
(582,'Órgano Dictaminador de la Alcaldía Tlalpan'),
(583,'Sandra Xantall Cuevas Nieves'),
(584,'Medio de Comunicación “EFEKTO INFORMATIVO”'),
(585,'Sandra Xantall Cuevas Nieves, en su calidad de Titular de la Alcaldía Cuauhtémoc'),
(586,'Eduardo Santillán Pérez, otrora persona candidata a la Alcaldía Álvaro Obregón y otras personas'),
(587,'Alcaldía Tlalpan y otras personas'),
(588,'Diana Catalina Consuelos López'),
(589,'Concejo de Gobierno del Pueblo de San Luis Tlaxialtemalco'),
(590,'Alejandro Rojas Durán'),
(591,'Medio de Comunicación Digital “De Reporteros”'),
(592,'Partido Acción Nacional'),
(593,'Mauricio Tabe Echartea, precandidato del Partido Acción Nacional de la Ciudad de México, así como Partido Acción Nacional'),
(594,'Néstor Núñez López, otrora Alcalde de Cuauhtémoc y otras personas'),
(595,'Héctor Guijosa Mora, en su carácter de Asesor Ejecutivo del Director General de Petróleos Mexicanos y el Partido MORENA'),
(596,'Gabriela Osorio Hernández, Diputada del Congreso de la Ciudad de México'),
(597,'Instituto Electoral de la Ciudad de México y Secretaría de Pueblos y Barrios Originarios y Comunidades Indígenas Residentes en la Ciudad de México.'),
(598,'Mariana Aidé Ortega Segovia, persona candidata a una Diputación del Congreso de la Ciudad de México y otras personas'),
(599,'Secretaría Administrativa del Instituto Electoral de la Ciudad de México.'),
(600,'Alcaldía Iztapalata'),
(601,'Karla Valeria Gómez Blancas, candidata a la Alcaldía en Milpa Alta.'),
(602,'Alcaldía Xoxhimilco'),
(603,'Organo Dictaminador de la Alcaldía Azcapotzalco'),
(604,'Dirección Distrital 31 del IECM'),
(605,'Junta de Coordinación Política del Congreso de la Ciudad de México'),
(606,'Dirección Distritales 25 Instituto Electoral de la Ciudad de México'),
(607,'Laura Carrillo "N" y quien resulte responsable'),
(608,'Ulises Labrador Hernández Margo'),
(609,'Partido Redes Sociales Progresistas y otro'),
(610,'Medio de Comunicación "Capital CDMX"'),
(611,'Consejo Distrital 6 del Instituto Electoral de la Ciudad de México'),
(612,'Consejo General y Consejo Distrital 13, ambos del Instituto Electoral de la Ciudad de México'),
(613,'Consejo Distrital 4 del Instituto Electoral de la Ciudad de México'),
(614,'Consejo Distrital 9 del Instituto Electoral de la Ciudad de México'),
(615,'Comité Ejecutivo Nacional y/o Comisión Permanente Nacional del Partido Acción Nacional'),
(616,'Dirección Distrital 5 del IECM'),
(617,'Armando Ramírez'),
(618,'Consejo Distrital 5 del Instituto Electoral de la Ciudad de México'),
(619,'Dirección Distrital 24 del IECM'),
(620,'Comisión de Justicia del Consejo Nacional del Partido Acción Nacional y otros'),
(621,'Consejo Distrital 3 del Instituto Electoral de la Ciudad de México'),
(622,'Personas de la red social X, usuario @anapatam_mxm y @rthur013'),
(623,'Jueza del Sistema Procesal Acusatorio adscrita a la Unidad de Gestión Judicial número ocho del Tribunal Superior de Justicia de la Ciudad de México'),
(624,'Consejo Distrital 8 del Instituto Electoral de la Ciudad de México'),
(625,'Presidente del Órgano Dictaminador de la Alcaldía Iztapalapa'),
(626,'Secretaría de la Contraloría General de la Ciudad de México'),
(627,'Consejo Distrital 2 del Instituto Electoral de la Ciudad de México'),
(628,'Consejo Distrital 1 del Instituto Electoral de la Ciudad de México'),
(629,'Consejo Distrital 7 del Instituto Electoral de la Ciudad de México'),
(630,'Consejos Distritales 19 y 25 del Instituto Electoral de la Ciudad de México'),
(631,'Dirección Distrital 33 y Secretaría Ejecutiva ambas del Instituto Electoral de la Ciudad de México'),
(632,'Presidenta, Tesorera, Secretaria y Vocal del Comité Pro-Panteón del Pueblo de San Gregorio Atlapulco'),
(633,'Consejo Distrital 24'),
(634,'Consejo Distrital 22'),
(635,'Enlace Auxiliar en San Miguel Ajusco y Alcaldía Tlalpan'),
(636,'Miguel Torruco Garza, en su calidad de Diputado Federal'),
(637,'Junta Cívica del Pueblo de Santo Tomás Ajusco'),
(638,'Patricia Elena Aceves Pastrana, Alcaldesa en Tlalpan y otras personas'),
(639,'Dirección Distrital 30 del Instituto Electoral de la Ciudad de México y otro'),
(640,'Toshimi Jacob Hira Ugalde, otrora persona candidata del partido Redes Sociales Progresista a la Alcaldía Gustavo A. Madero y otra persona'),
(641,'Pablo Raúl Moreno Carrión, Joana Marín Salazar, otroras personas candidatas a la Alcaldía Iztacalco y el Partido Redes Sociales Progresistas'),
(642,'Comité Ejecutivo Nacional de Morena'),
(643,'Partido Revolucionario Institucional Consejo Distrital 7 del Instituto Electoral de la Ciudad de México'),
(644,'Dirección Distrital 32 del IECM'),
(645,'Santiago Taboada Cortina y quienes resultes responsables'),
(646,'Clara Marina Brugada Molina'),
(647,'Junta Cívica de San Lorenzo Huipulco'),
(648,'Dirección Distrital 12 del Instituto Electoral de la Ciudad de México y Órgano Dictaminador de la Alcaldía Tlalpan'),
(649,'Santiago Taboada Cortina, otrora alcalde de Benito Juárez'),
(650,'Junta Cívica Electoral del Pueblo de San Pedro Mártir'),
(651,'Clara Marina Brugada Molina y otras personas'),
(652,'Juan Manuel Astudillo'),
(653,'Alcaldía Coyoacán y otras'),
(654,'María Clemente García Moreno también Diputada del Congreso de la Ciudad de México y de quien o quienes resulten responsables'),
(655,'Junta Cívica del Pueblo Originario de Chimalcoyoc, demarcación Tlalpan'),
(656,'Comisión Permanente del Consejo Nacional del Partido Acción Nacional y otros'),
(657,'Omar Mariel Tripp Reyna y otras personas, integrantes de la Dirección Ejecutiva Estatal del Partido de la Revolución Democrática de la Ciudad de México'),
(658,'Clara Marina Brugada Molina, otrora alcaldesa de Iztapalapa y Coordinadora de la Defensa de la Transformación de la Ciudad de México'),
(659,'Dirección Distrital 17 del Instituto Electoral de la Ciudad de México y el Órgano Dictaminador de la Alcaldía Benito Juárez'),
(660,'Junta Cívica del Pueblo de San Miguel Topilejo y Alcaldía Tlalpan'),
(661,'El Universal compañía periodística nacional'),
(662,'Comisión de Participación Comunitaria (COPACO) Unidad Territorial Asturias, clave 15-002.'),
(663,'Partido Morena y Víctor Hugo Romo de Vivar Guerra, Alcalde en Miguel Hidalgo.'),
(664,'Dirección Distrital 05 del Instituto Electoral de la Ciudad de México'),
(665,'Dirección Distrital 16 del Instituto Electoral de la Ciudad de México'),
(666,'Clara Marina Brugada Molina, otrora alcaldesa de Iztapalapa'),
(667,'Partidos Morena y Movimiento Ciudadano'),
(668,'María del Carmen Pacheco Gamiño, persona candidata al mismo cargo'),
(669,'Dirección Distrital 16 del Instituto Electoral de la Ciudad México'),
(670,'Comité Ejecutivo Estatal de MORENA en la Ciudad de México y otras personas'),
(671,'Junta Cívica del Pueblo de San Lorenzo Huipulco'),
(672,'Órgano Dictaminador en la Alcaldía Miguel Hidalgo'),
(673,'Clara Marina Brugada Molina y otro'),
(674,'Ricardo Janecarlo Lozano Reynoso, Diputado Local de la Demarcación Gustavo A. Madero y otros 3'),
(675,'Comisión Permanente de Quejas del Instituto Electoral de la Ciudad de México y otro'),
(676,'Órgano Dictaminador en la Alcaldía Álvaro Obregón'),
(677,'Órgano Dictaminador en la Alcaldía Tlalpan'),
(678,'Dirección Distrital 13 del Instituto Electoral de la Ciudad de México'),
(679,'Direccion Distrital 17 del Instituto Electoral de la Ciudad de México'),
(680,'Carlos Alberto Ulloa Pérez, en su calidad de Titular de la Secretaría de Desarrollo Urbano y Vivienda de la Ciudad de México'),
(681,'Autoridad Responsable: Instituto Electoral de la Ciudad de México'),
(682,'Judith Vanegas Tapia Alcaldesa de Milpa Alta y otro'),
(683,'Pablo Trejo Pérez, en su calidad de Director General de Administración de la Alcaldía Gustavo A. Madero'),
(684,'Karla Valeria Gómez Blancas Candidata a Alcaldesa en Milpa Alta'),
(685,'Diario Alebrije y Quien resulte responsable'),
(686,'Órgano Dictamnador de la Alcaldía Iztapalapa'),
(687,'Dirección Distrital 29 del Instituto Electoral de la Ciudad de México'),
(688,'Partido Revolucionario Institucional en la Ciudad de México'),
(689,'Eduardo Santillán Pérez y otras personas'),
(690,'Órgano Dictaminador de la Alcaldía Xochimilc'),
(691,'Nora del Carmen Bárbara Arias Contreras, Presidenta de la Dirección Estatal Ejecutiva del Partido de la Revolución Democrática en la Ciudad de México y otras personas'),
(692,'Alcaldía Tlapan y Comisariado Ejidal del Pueblo San Miguel Xicalco'),
(693,'Rubén Linares Flores, Director General de Desarrollo Social de la Alcaldía Gustavo A. Madero'),
(694,'José Luis Rodríguez Díaz de León, Candidato a Diputado del Congreso de la Ciudad de México.'),
(695,'Víctor Hugo Romo de Vivar Guerra, Alcalde en Miguel Hidalgo y otra persona.'),
(696,'Órgano Dictaminador de la Alcaldía Alvaro Obregón'),
(697,'Órgano Dictaminador de la Alcaldía Benito Juáre'),
(698,'Jorge Emilio Sánchez Cordero Grossmann.'),
(699,'Consejo Electoral del Pueblo de Santa Ana Tlacotenco en Milpa Alta'),
(700,'Alberto Esteva Salinas, Alcalde en funciones en Álvaro Obregón'),
(701,'Alberto Esteva Salinas, Alcalde en Álvaro Obregón.'),
(702,'Partido MORENA.'),
(703,'Erick Alejandro Reyes León, Director General de Gobierno de la Alcaldía Álvaro Obregón.'),
(704,'Ulises Labrador Hernández Magro, candidato a Diputado Local por el Distrito 13, postulado por la candidatura común de los Partidos Políticos Morena y del Trabajo'),
(705,'Jorge Alvarado Galicia, Alcalde en Milpa Alta y otras personas'),
(706,'Nury Delia Ruiz Ovando'),
(707,'José Octavio Rivero Villaseñor, en su calidad de Alcalde en Milpa Alta'),
(708,'Víctor Hugo Romo de Vivar Guerra, Alcalde en Miguel Hidalgo y Gustavo García Arias, Director Jurídico en la misma Demarcación'),
(709,'Dirección Distrital 28 del Instituto Electoral de la Ciudad de México'),
(710,'Mauricio Tabe Echartea, precandidato del Partido Acción Nacional al cargo de Alcalde en Miguel Hidalgo y el Partido Acción Nacional'),
(711,'Eduardo Santillán Pérez Diputado del Congreso de la Ciudad de México'),
(712,'Comisión Nacional de Elecciones y Comisión Nacional de Encuestas, ambas de MORENA'),
(713,'Dirección Distrital 26 del Instituto Electoral de la Ciudad de México y otro'),
(714,'Eduardo Santillán Pérez, Diputado del Congreso de la Ciudad de México'),
(715,'Víctor Hugo Romo de Vivar Guerra, en su calidad de candidato a la Alcaldía de Miguel Hidalgo, los Partidos Morena, del Trabajo y Verde Ecologista de México y otros'),
(716,'Clara Marina Brugada Molina, Precandidata a la Jefatura de Gobierno por la Coalición que Integran los Partidos Políticos MORENA, del Trabajo y Verde Ecologista de México'),
(717,'Autoridad Responsable: Pleno del Tribunal Electoral de la Ciudad de México'),
(718,'Jorge Núñez Becerril y otras personas'),
(719,'Teodoro Alonso Paniagua y Medio de Comunicación “El Big Data MX”'),
(720,'Dirección Distrital 04 del Instituto Electoral de la Ciudad de México'),
(721,'Órgano Dictaminador de la Alcaldía Tlalpan y Dirección Distrital 14 del Instituto Electoral de la Ciudad de México'),
(722,'Patricia Elena Aceves Pastrana, Alcaldesa de Tlalpan y otras personas'),
(723,'Grupo de personas que emiten la Convocatoria de seis de mayo de dos mil veinticuatro, en el Pueblo Originario de San Pedro Mártir, Tlalpan'),
(724,'Judith Vanegas Tapia Candidata a Alcaldesa de Milpa Alta y otro'),
(725,'Sergio Flores Ríos, persona candidata a la Alcaldía Xochimilco y el Partido Movimiento Ciudadano'),
(726,'Concejo de Gobierno Comunitario de San Andres Totoltepec'),
(727,'Concejo de Gobierno Comunitario de San Andrés Totoltepec'),
(728,'Comisión de Administración y Procuración de Justicia del Congreso de la Ciudad de México'),
(729,'Dirección Distrital 02 del Instituto Electoral de la Ciudad de México'),
(730,'Comisión Permanente de Asociaciones Políticas del Instituto Electoral de la Ciudad de México y otro'),
(731,'El Big Data'),
(732,'Víctor Hugo Romo de Vivar Guerra, en su calidad de candidato a la Alcaldía en Miguel Hidalgo y otras personas.'),
(733,'Abraham Borden Camacho, encargado de Despacho y otro'),
(734,'Sergio Flores Ríos, en su calidad de Candidato a la Alcaldía Xochimilco por el Partido Movimiento Ciudadano'),
(735,'María Guadalupe Chávez Contreras en su calidad de entonces Diputada Local'),
(736,'Rocío Barrera Badillo, persona candidata a la Alcaldía en Venustiano Carranza'),
(737,'Autoridad Responsable: Secretaría Administrativa del Instituto Electoral de la Ciudad de México'),
(738,'Rafael Márquez Méndez en su Carácter de Candidato a Alcalde en Iztacalco y otras personas'),
(739,'Partido Movimiento Ciudadano y otra persona'),
(740,'Alberto Esteva Salinas, Alcalde en Álvaro Obregón'),
(741,'Carlos Alonso Castillo, persona Diputad del Congreso de la Ciudad de México y candidata a titular de la Alcaldía Coyoacán'),
(742,'María de los Dolores Padierna Luna, en su carácter de persona Diputada federal y Vicepresidenta de la Mesa Directiva de la Cámara de Diputados del Congreso de la Unión'),
(743,'Congreso de Unión de la Ciudad de México'),
(744,'Kevin Castañeda Amador, Esmeralda Morales Naranjo personas Capacitadoras Asistentes Electorales'),
(745,'Partido Político Redes Sociales Progresistas y otro'),
(746,'Héctor Guijosa Mora'),
(747,'Francisco Chiguíl Figueroa Alcalde de Gustavo A. Madero'),
(748,'Gabriela Osorio Hernández, Diputada del Congreso de la Ciudad'),
(749,'Comisión Nacional de Honestidad y Justicia del Partido MORENA y otras'),
(750,'Secretaría General del Comité Ejecutivo Nacional del Partido Acción Nacional'),
(751,'Patricia Jimena Ortiz Couturier persona candidata a la Alcaldía La Magdalena Contreras por los Partidos MORENA, del Trabajo y Verde Ecologista de México y otra persona'),
(752,'Mauricio Tabe Echartea, candidato a Alcalde en Miguel Hidalgo'),
(753,'Mauricio Tabe Echartea, Candidato a la Alcaldía Miguel Hidalgo y el Partido Acción Nacional'),
(754,'Araceli Berenice Hernández Calderón, en su calidad de candidata a Alcaldesa en Tláhuac'),
(755,'Víctor Hugo Romo de Vivar Guerra, Alcalde de Miguel Hidalgo y otra persona'),
(756,'Dirección General de Participación Ciudadana de la Alcaldía Xochimilco'),
(757,'Secretaría de Medio Ambiente del Gobierno de la Ciudad de México'),
(758,'Partido Verde Ecologista de México'),
(759,'Héctor Hugo Hernández Rodríguez persona candidata a la Alcaldía Tlalpan'),
(760,'Jorge Gaviño Ambriz, persona candidata a la Diputación por el Distrito Electoral Uninominal 6'),
(761,'Alejandro Durán Raña, persona candidata a la Alcaldía Tláhuac'),
(762,'Órgano Interno de Control de la Alcaldía Miguel Hidalgo'),
(763,'Jorge Emilio Sánchez Cordero'),
(764,'Dirección Distrital 9 del Instituto Electoral de la Ciudad de México'),
(765,'Comisión Permanente de Asociaciones Políticas del Instituto Electoral de la Ciudad de México.'),
(766,'Alberto Esteva Salinas, Alcalde en funciones de Álvaro Obregón y otras personas'),
(767,'Alicia Amalia Sobrado González'),
(768,'Penélope Campos González, persona candidata a una diputación por el distrital electoral 17.'),
(769,'Concejo de la Alcaldía Coyoacán'),
(770,'Alejandro Ugalde González, Subdelegado como autoridad representativa del Pueblo de San Bartolo Ameyalco'),
(771,'Miguel Ángel Morales Norberto, candidato suplente a Diputado local del Distrito VI'),
(772,'Rafael Márquez, persona candidato a la Alcaldía Iztacalco.'),
(773,'Víctor Hugo Romo de Vivar Guerra, persona candidata a la titularidad de la Alcaldía Miguel Hidalgo y otra persona.'),
(774,'Partido Verde Ecologista de México y Partido de la Revolución Democrática'),
(775,'Víctor Hugo Romo de Vivar Guerra, persona candidata a la titularidad de la Alcaldía Miguel Hidalgo y otras personas'),
(776,'Dirección Distrital 18 del Instituto Electoral de la Ciudad de México'),
(777,'Ulises Labrador Hernández Magro, persona candidata a una Diputación al Congreso de la Ciudad de México postulado por la candidatura en común “JUNTOS HACEMOS HISTORIA”, y otras personas'),
(778,'Presidente y Secretario de Órgano Desconcentrado de la Dirección Distrital 18 del Instituto Electoral de la Ciudad de México'),
(779,'Alcaldía Tlalpan y la Comisión Redactora del Pueblo de San Pedro Mártir'),
(780,'Raúl Armando Quintero Martínez, persona candidata a la titularidad de la Alcaldía Iztacalco por la candidatura común “Juntos Hacemos Historia Ciudad de México” por los Partidos Morena y del Trabajo'),
(781,'Asociación Civil “La Voz de Polanco A.C.”'),
(782,'Ulises Labrador Hernández Magro, persona candidata a una Diputación Local por el Distrito Electoral 13 y quien o quienes resulten responsables.'),
(783,'Pía Daniela Herrera Mistreta, persona candidata a un Diputación al Congreso de la Ciudad de México postulada por el Partido Verde Ecologista y otra'),
(784,'Clara Marina Brugada Molina, persona candidata a la titularidad de la Alcaldía Iztapalapa por los Partidos Políticos Morena y del Trabajo'),
(785,'Eduardo Santillán Pérez, en su calidad de persona candidata como titular de la Alcaldía Álvaro Obregón Álvaro Obregón postulada por la Candidatura Común “Juntos Hacemos Historia”'),
(786,'Víctor Hugo Romo de Vivar Guerra, en su calidad de persona candidata como titular de la Alcaldía Miguel Hidalgo'),
(787,'Consejos Distritales 19 y 25 Instituto Electoral de la Ciudad de México'),
(788,'Eduardo Santillán Pérez, en su calidad de persona candidata a la Alcaldía Álvaro Obregón Álvaro Obregón postulada por la Candidatura Común “Juntos Hacemos Historia” y otras personas'),
(789,'Comité Electoral del Pueblo San Jerónimo Miacatlán'),
(790,'Dirección Distrital 5 del Instituto Electoral de la Ciudad de México y el Órgano Dictaminador de la Alcaldía Azcapotzalco'),
(791,'Maxta González Carrillo, persona candidata a la Diputación local por el Distrito Electoral 12 por los Partidos Acción Nacional, Revolucionario Institucional y de la Revolución Democrática'),
(792,'Carlos Hernández Mirón, Diputado del Congreso de la Ciudad de México'),
(793,'María de los Dolores Padierna Luna, en su calidad de persona candidata a la Alcaldía Cuauhtémoc'),
(794,'José Giovanni Gutiérrez Aguilar, persona candidata a la Alcaldía Coyoacán'),
(795,'Partidos del Trabajo y Movimiento Ciudadano'),
(796,'Elizabeth Mateos Hernández, persona candidata a una Diputación Local del Distrito Electoral 15.'),
(797,'Esther Silvia Barrios Sánchez persona candidata a la Diputación Local del Distrito Electoral 9.'),
(798,'Guadalupe Chávez y Gustavo Nabor Ojeda Delgado, personas candidatas a una Diputación por el Distrito Electoral 19 y otras personas'),
(799,'Héctor Hugo Hernández Rodríguez, persona candidata a la Alcaldía Tlalpan postulada por el Partido Movimiento Ciudadano'),
(800,'Autoridades Tradicionales del Pueblo de Santiago Tulyehualco, Alcaldía Xochimilco e Instituto Electoral de la Ciudad de México'),
(801,'Ana Julia Hernández Pérez'),
(802,'Víctor Hugo Romo de Vivar Guerra, persona candidata a la Alcaldía Miguel Hidalgo y otras personas'),
(803,'Dirección Distrital 15 del Instituto Electoral de la Ciudad de México'),
(804,'Consejo de Gobierno Comunitario del Pueblo de San Andrés Totoltepec y otras personas'),
(805,'Leonardo Ortiz Heras, precandidato a titular de Alcaldía Álvaro Obregón postulado por Morena'),
(806,'Dirección Distrital 5 del Instituto Electoral de la Ciudad de México'),
(807,'Dirección Distrital 22 del Instituto Electoral de la Ciudad de México'),
(808,'Órgano Dictaminador de la Alcaldía Xochimilco y la Dirección Distrital 19 del Instituto Electoral de la Ciudad de México'),
(809,'Órgano Dictaminador de la Alcaldía Tlalpan y la Dirección Distrital 16 del Instituto Electoral de la Ciudad de México'),
(810,'Órgano Dictaminador de la Alcaldía Ávaro Obregón y la Dirección Distrital 18 del Instituto Electoral de la Ciudad de México'),
(811,'Órgano Dictaminador de la Alcaldía Iztapalapa y la Dirección Distrital 21 del Instituto Electoral de la Ciudad de México'),
(812,'Rocío Barrera Badillo persona candidata a la Alcaldía Venustiano Carranza por la candidatura común “Vamos por la CDMX”'),
(813,'Órgano Dictaminador de la Alcaldía Xochimilco y la Dirección Distrital 25 del Instituto Electoral de la Ciudad de México'),
(814,'Órgano Dictaminador de la Alcaldía Álvaro Obregón y la Dirección Distrital 23 del Instituto Electoral de la Ciudad de México'),
(815,'Órgano Dictaminador de la Alcaldía Iztapalapa y la Dirección Distrital 29 del Instituto Electoral de la Ciudad de México'),
(816,'Órgano Dictaminador de la Alcaldía Iztapalapa y la Dirección Distrital 22 del Instituto Electoral de la Ciudad de México'),
(817,'Órgano Dictaminador de la Alcaldía Gustavo A. Madero y la Dirección Distrital 1 del Instituto Electoral de la Ciudad de México'),
(818,'Órgano Dictaminador de la Alcaldía Azcapotzalco y la Dirección Distrital 3 del Instituto Electoral de la Ciudad de México'),
(819,'Órgano Dictaminador de la Alcaldía Azcapotzalco y la Dirección Distrital 5 del Instituto Electoral de la Ciudad de México'),
(820,'Órgano Dictaminador de la Alcaldía Benito Juárez y la Dirección Distrital 17 del Instituto Electoral de la Ciudad de México'),
(821,'Órgano Dictaminador de la Alcaldía Benito Juárez y la Dirección Distrital 26 del Instituto Electoral de la Ciudad de México'),
(822,'Órgano Dictaminador de la Alcaldía Álvaro Obregón y la Dirección Distrital 18 del Instituto Electoral de la Ciudad de México'),
(823,'Órgano Dictaminador de la Alcaldía Coyoacán y la Dirección Distrital 30 del Instituto Electoral de la Ciudad de México'),
(824,'José Manuel Ballesteros López, alcalde en funciones de Venustiano Carranza y otras personas'),
(825,'Órgano Dictaminador de la Alcaldía Cuauhtémoc y la Dirección Distrital 12 del Instituto Electoral de la Ciudad de México'),
(826,'Partidos del Trabajo y Morena'),
(827,'Órgano Dictaminador de la Alcaldía Coyoacán y la Dirección Distrital 32 del Instituto Electoral de la Ciudad de México'),
(828,'Órgano Dictaminador de la Alcaldía Iztapalapa y la Dirección Distrital 28 del Instituto Electoral de la Ciudad de México'),
(829,'Eduardo Santillán Pérez, persona candidata a la Alcaldía Álvaro Obregón y otras personas'),
(830,'Mauricio Tabe Echartea, el Partido Acción Nacional y el Medio de Comunicación “NTCD”'),
(831,'Órgano Dictaminador de la Alcaldía Tlalpan y la Dirección Distrital 19 del Instituto Electoral de la Ciudad de México'),
(832,'Partido Acción Nacional y otra persona.'),
(833,'Persona Encargada del Despacho y la Subdirectora de Limpia de la Alcaldía Miguel Hidalgo.'),
(834,'Comité Pro Panteón del Pueblo de San Gregorio Atlapulco de la Demarcación Xochimilco'),
(835,'Órgano Dictaminador de la Alcaldía Coyoacán y la Dirección Distrital 26 del Instituto Electoral de la Ciudad de México'),
(836,'Comisión de Organización Electoral y Geoestadística del IECM, Junta Cívica Electoral del Pueblo Originario de San Pedro Mártir, Tlalpan'),
(837,'Órgano Dictaminador de la Alcaldía Iztapalapa y la Dirección Distrital 24 del Instituto Electoral de la Ciudad de México'),
(838,'Dirección Distrtial 15 del Instituto Electoral de la Ciudad de México'),
(839,'José Alberto Benavides Castañeda, persona candidata a Diputación del Congreso de la Ciudad de México'),
(840,'Sandra Xantall Cuevas Nieves, persona candidata a la Alcaldía Cuauhtémoc'),
(841,'Dirección Distrital 4 del Instituto Electoral de la Ciudad de México'),
(842,'María de los Dolores Padierna Luna, persona candidata a la Alcaldía Cuauhtémoc por los Partidos Políticos del Trabajo y MORENA'),
(843,'Dirección Distrital 24 del Instituto Electoral de la Ciudad de México'),
(844,'Alicia Ana Lilia Robles Acevedo, persona candidata a la Alcaldía Milpa Alta'),
(845,'Giovanni Gutiérrez Aguilar, persona candidata a la Alcaldía Coyoacán'),
(846,'Patricia Urriza Arellano, persona candidata a la Alcaldía en Coyoacán y otras personas'),
(847,'José Gaviño Ambriz, persona candidata a la Diputación del Distrito Electoral 6 por la candidatura común “Va por México” y otra persona'),
(848,'Medio de Comunicación Capital CDMX'),
(849,'José Gonzalo Espina Miranda y Ricardo Rubio Torres, Diputados Integrantes del Grupo Parlamentario del Partido Acción Nacional'),
(850,'Dirección Distrital 01 del IECM'),
(851,'Direcciones Distrital 26 y 30 del IECM, Órgano Dictaminador de la Alcaldía Coyoacán'),
(852,'Partidos del Trabajo, Acción Nacional y de la Revolución Democrática'),
(853,'Partido del Trabajo'),
(854,'Alicia Amalia Sobrado González persona candidata al mismo cargo y otras personas'),
(855,'Secretaria Ejecutivia del Instituto Electoral de la Ciudad de México'),
(856,'Diego Orlando Garrido López persona candidata a una Diputación por el Partido Acción Nacional'),
(857,'Héctor Hugo Hernández persona candidata a la Alcaldía en Tlalpan postulado por el Partido Movimiento Ciudadano'),
(858,'Ulises Labrador Hernández y Yair Figueroa Sandoval, candidatos Propietario y Suplente a Diputados por el Distrito 13 por los Partidos MORENA y Del Trabajo'),
(859,'Araceli Berenice Hernández Calderón, persona candidata a la Alcaldía Tláhuac'),
(860,'Yuriri Ayala Zuñiga, persona candidata a una Diputación al Congreso de la Ciudad de México'),
(861,'Armando Ramírez “N”'),
(862,'Ana Julia Hernández Pérez y Miguel Ángel Cámara Arango, personas candidatas a una Diputación Local postuladas por el Partido Verde Ecologista de México'),
(863,'Mauricio Tabe Echartea persona candidata a la Alcaldía Miguel Hidalgo y el Partido Acción Nacional'),
(864,'Dirección Distrtial 7 del IECM'),
(865,'Alberto Esteva Salinas, persona titular de la Alcaldía y/o Encargado de Despacho en Álvaro Obregón'),
(866,'Persona Titular de la Unidad Técnica de Archivo, Logistica y Apoyo a Órganos Desconcentrados del Instituto Electoral de la Ciudad de México'),
(867,'José Emmanuel Vargas Bernal en su calidad de Diputado del Congreso de la Ciudad de México'),
(868,'Juan José Sánchez González, en su carácter de Director General de Bienestar Social en la Alcaldía La Magdalena Contreras'),
(869,'Gabriel del Monte Rosales, persona candidata a la titularidad de la Alcaldía en Xochimilco y otras personas'),
(870,'Noé Mejía Terán y otra persona'),
(871,'Secretaria Ejecutiva del Instituto Electoral de la Ciudad de México'),
(872,'Partido Acción Nacional y otra persona'),
(873,'Vania Elizabeth Mecatl Verduzco y otras personas candidatas postuladas por el Partido Encuentro Solidario'),
(874,'Mauricio Tabe Echartea, en su calidad de candidato a Alcalde en Miguel Hidalgo'),
(875,'Secretario de Órgano Desconcentrado de la Dirección Distrital 6 del Instituto Electoral de la Ciudad de México'),
(876,'José Carlos Acosta Ruiz, Alcalde en Xochimilco'),
(877,'Sandra Xantall Cuevas Nieves persona candidata a la titularidad de la Alcaldía Cuauhtémoc'),
(878,'Alcaldía Coyoacán y Contraloria de la CDMX'),
(879,'Jesús Sesma Suárez, Presidente del Partido Verde Ecologista de México en la Ciudad de México y persona candidata a una Diputación Local.'),
(880,'María Teresa Verónica Cantú Elizarrarás'),
(881,'Irma Fabiola Bautista Guzmán, persona candidata a la titularidad de la Alcaldía Iztacalco y otras personas'),
(882,'Eduardo Santillán Pérez, en su calidad de Diputado del Congreso de la Ciudad de México'),
(883,'Secretaría Ejecutiva del IECM'),
(884,'Subdelegado de Santa Úrsula Xitla, Demarcación en Tlalpan'),
(885,'Dirección Distrital 32 del Instituto Electoral de la Ciudad de México'),
(886,'Santiago Taboada Cortina persona candidata a la titularidad de la Alcaldía Benito Juárez postulado por el Partido Acción Nacional'),
(887,'Julio César Moreno Rivera, titular con licencia de la Alcaldía Venustiano Carranza'),
(888,'Ricardo Janecarlo Lozano Reynoso persona candidata del Partido de la Revolución Democrática al mismo cargo'),
(889,'Otros'),
(890,'Dirección Distrital 8 del IECM'),
(891,'Rodrigo Menéndez Roldan, persona candidata a Diputación del Congreso de la Ciudad de México'),
(892,'José Carlos Acosta Ruiz, Alcalde en Xochimilco y otra persona'),
(893,'Gabriela Osorio Hernández, persona candidata a la titularidad de la Alcaldía Tlalpan postulada por la candidatura común de los Partidos MORENA y del Trabajo'),
(894,'Autoridad Tradicional del Pueblo de San Gregorio Atlapulco, Demarcación Xochimilco'),
(895,'Persona Titular de la Unidad Técnica de Archivo, Logistica y Apoyo a los Órganos Desconcentrados del Instituto Electoral de la Ciudad de México'),
(896,'María del Carmen Pacheco Gamiño, persona candidata a titular de la Alcaldía Gustavo A. Madero'),
(897,'Sandra Xantall Cuevas Nieves, persona candidata a la titularidad de la Alcaldía en Cuauhtémoc'),
(898,'Alfa Eliana González Magallanes persona candidata a Alcaldesa en Tlalpan'),
(899,'Alcaldía Cuajimalpa de Morelos'),
(900,'José Octavio Rivero Villaseñor, persona candidata a Diputación en el Distrito Electoral 7'),
(901,'Víctor Hugo Romo de Vivar Guerra, persona candidata a la Alcaldía Miguel Hidalgo'),
(902,'Xóchitl Bravo Espinosa'),
(903,'Dirección Distrital 02 de Instituto Electoral de la Ciudad de México'),
(904,'Alberto Esteva Salinas, Alcalde en Álvaro Obregón y otra persona'),
(905,'Luis Gerardo Quijano Morales, persona candidata a la Alcaldía La Magdalena Contreras'),
(906,'Clara Marina Brugada Molina persona candidata a la Alcaldía Iztapalapa, postulada por la candidatura en común “Juntos Hacemos Historia Ciudad de México”'),
(907,'Dirección Distrital 12 de Instituto Electoral de la Ciudad de México'),
(908,'Dirección Distrital 3 del Instituto Electoral de la Ciudad de México y Órgano Dictaminador de la Alcaldía Azcapotzalco'),
(909,'Jorge Gaviño Ambriz y Miguel Ángel Morales Norberto, otroras personas candidatos propietario y suplente a una Diputación del Congreso de la Ciudad de México'),
(910,'Adolfo Llubere Sevilla y el Partido Fuerza por México'),
(911,'José Giovanni Gutiérrez Aguilar, otrora persona candidata a la Alcaldía Coyoacán'),
(912,'Patronato Originario de San Andrés Totoltepec, Tlalpan'),
(913,'Paula Adriana Soto Maldonado y otras personas'),
(914,'Concejo de Gobierno Comunitario del Pueblo de San Andrés Totoltepec'),
(915,'Héctor Hugo Hernández Rodríguez, persona candidata a Alcalde en Tlalpan y otra persona'),
(916,'María de Lourdes Paz Reyes, Diputada y Presidenta de la Comisión de Salud del Congreso de la Ciudad y México y persona candidata a la Diputación en el Distrito Electoral 11 de la Ciudad de México'),
(917,'Gabriel del Monte Rosales. persona aspirante a la candidatura sin partido a la Alcaldía Xochimilco'),
(918,'Víctor Hugo Romo de Vivar Guerra, otrora persona candidata a la Alcaldía Miguel Hidalgo postulado por los Partidos MORENA, del Trabajo y Verde Ecologista de México y otras personas.'),
(919,'Sentencia de 2 de junio de 2023'),
(920,'Dirección Distrital 15 del Instituto Electoral de la Ciudad de México y otra persona'),
(921,'Jorge Gaviño Ambriz persona candidata a una Diputación en el Distrito Electoral 6 y otras personas'),
(922,'Instituto Electoral de la Ciudad de México y otra persona'),
(923,'Cuauhtémoc Martínez Laguna, candidata a la Alcaldía Milpa Alta y al Partido Fuerza por México.'),
(924,'Dirección Distrital 11 del Instituto Electoral de la Ciudad de México'),
(925,'Dirección de Participación Ciudadana de la Alcaldía La Magdalena Contreras'),
(926,'Gabriela Osorio Hernández, otrora persona candidata a la Alcaldía en Tlalpan y otras personas.'),
(927,'Sofía García Silva, persona candidata a Diputación al Congreso de la Ciudad de México, postulada por el Partido Redes Sociales Progresistas'),
(928,'Secretaria de Pueblos y Barrios Originario de la Ciudad de México'),
(929,'Dirección Distrital 02 Cabecera de Demarcación en Gustavo A. Madero'),
(930,'Jesús Sesma Juárez, Partido Verde Ecologista de México y/o quien resulte responsable'),
(931,'Carlos Alonso Castillo Pérez y otras personas'),
(932,'Concejo de Gobierno Comunitario del Pueblo Originario de San Andrés Totoltepec.'),
(933,'Dirección Distrital 25 del Instituto Electoral de la Ciudad de México y Alcaldía Xochimilco'),
(934,'Ulises Labrador Hernández Magro, Director Ejecutivo de Participación Ciudadana en la Alcaldía Miguel Hidalgo'),
(935,'Integrantes del “Concejo de Gobierno Comunitario” de San Andrés Totoltepec, Tlalpan'),
(936,'Consejo General del Instituto Electoral de la Ciudad de México.'),
(937,'José Carlos Acosta Ruiz, persona candidata a la Alcaldía en Xochimilco'),
(938,'Víctor Hugo Romo de Vivar Guerra, otrora persona candidata a la Alcaldía Miguel Hidalgo postulada por los Partidos MORENA, del Trabajo y Verde Ecologista de México'),
(939,'Dirección Distrital 12 del Instituto Electoral de la Ciudad de México y otras personas'),
(940,'Jorge Triana Tena'),
(941,'Alcaldía Xochimilco y el Instituto Electoral de la Ciudad de México'),
(942,'Comisión de Asociaciones Políticas del Instituto Electoral de la Ciudad de México'),
(943,'Alcaldía Tlalpan y Concejo General de los Pueblos'),
(944,'Comisiones Unidas de Planeación del Desarrollo y de Administración Pública Local del Congreso de la Ciudad de México'),
(945,'Mario Horacio Maldonado Padilla, Periodista'),
(946,'ciudadano'),
(947,'Alejandro Duran Raña, otrora persona candidata a la Alcaldía Tláhuac postulada por los partidos Revolucionario Institucional, de la Revolución Democrática y otras personas'),
(948,'Armando Quintero Martínez en su carácter de Alcalde en Iztacalco.'),
(949,'Directora General de Construcción de Ciudadanía, Consejo Electoral 2016-2019 y Consejo Electoral 2019-2021 en funciones, todos de la Alcaldía Milpa Alta'),
(950,'María de los Dolores Padierna Luna persona candidata a Alcaldesa en Cuauhtémoc y otras personas'),
(951,'Alberto Castro Arrona persona candidato a Concejal en la Alcaldía Gustavo A. Madero postulado por el Partido Movimiento Ciudadano y otra persona'),
(952,'Víctor Hugo Romo de Vivar Guerra, otrora persona candidata a la Alcaldía Miguel Hidalgo y los partidos Monera, del Trabajo y Verde Ecologista'),
(953,'Dirección Distrital 26 y Secretaría Ejecutiva, ambas del Instituto Electoral de la Ciudad de México'),
(954,'Mario Santeliz Martínez y Elizabeth Mateos Hernández personas candidatas a una Diputación por los Distritos Electorales 11 y 15 postulados por el Partido Verde Ecologista y otra persona'),
(955,'Junta Cívica de Santa Úrsula Xitla'),
(956,'Lía Limón García, otrora persona candidata a la Alcaldía Álvaro Obregón postulada por los Partidos Acción Nacional y Revolucionario Institucional y otras personas'),
(957,'Luis Alberto Chávez García otrora persona candidata a una Diputación en el Distrito 14 postulada por el Partido Acción Nacional y otras personas'),
(958,'Jorge Alvarado Galicia y otra persona'),
(959,'José Giovanni Gutiérrez Aguilar persona candidata a Alcalde en Coyoacán y otras personas'),
(960,'Concejo General de los Pueblos y la Alcaldía de Tlalpan'),
(961,'Consejo General de los Pueblos de Tlalpan'),
(962,'Dirección General de Participación Ciudadana de la Alcaldia Tláhuac'),
(963,'Concejo General de los Pueblos y Alcaldía Tlalpan'),
(964,'Partido Fuerza por México'),
(965,'Santiago Taboada Cortina, otrora alcalde con licencia de Benito Juárez y candidato a la Alcaldía de esa Demarcación postulado por el Partido Acción Nacional y otra persona'),
(966,'Vidal Llerenas Morales otrora persona candidata a la titularidad de la Alcaldía Azcapotzalco postulada por la candidatura común “Juntos Hacemos Historia Ciudad de México”'),
(967,'José Carlos Acosta Ruiz, persona candidata a la titularidad de la Alcaldía Xochimilco, postulada por el Partido MORENA'),
(968,'Andrés Atayde Rubiolo, presidente del Partido Acción Nacional en la Ciudad de México y otras personas'),
(969,'Adolfo Llubere Sevilla, persona candidata a la Alcaldía Tlalpan postulada por el Partido Fuerza por México'),
(970,'Secretaría Ejecutiva y Dirección Ejecutiva de Asociaciones Políticas y Fiscalización, ambas del Instituto Electoral de la Ciudad de México'),
(971,'Gabriela Osorio Hernández, persona candidata a titular de la Alcaldía de Tlalpan'),
(972,'Coordinador de Enlace Territorial del Pueblo San Pablo Oztotepec, Demarcación Milpa Alta'),
(973,'Alessandra Rojo de la Vega Piccolo, Diputada del Congreso de la Ciudad de México'),
(974,'Paula Adriana Soto Maldonado, persona candidata a la Alcaldía Benito Juárez y otras personas'),
(975,'Janet de Luna Jiménez, persona encargada de despacho de la Alcaldía Azcapotzalco'),
(976,'Jorge Real Sánchez y otras personas'),
(977,'Francisco Javier Saldívar Camacho, otrora persona candidata a la Alcaldía Cuajimalpa, por la candidatura común “Juntos hacemos Historia Ciudad de México”'),
(978,'Comité Ejecutivo Nacional y la Secretaría de Organización, ambos del Partido Morena'),
(979,'Direción Distrital 25 del Instituto Electoral de la Ciudad de México'),
(980,'Pleno del Tribunal Electoral de la Ciudad de México.'),
(981,'Eduardo Santillán Pérez, otrora persona candidata a la titularidad de la Alcaldía Álvaro Obregón'),
(982,'Evaristo Roberto Candia Ortega y otras personas'),
(983,'Alcaldía de Tlalpan'),
(984,'Dirección de Participación Ciudadana de la Alcaldía de Tlalpan'),
(985,'Evelyn Parra Álvarez, persona candidata a titular de la Alcaldía en Venustiano Carranza, en candidatura común, integrada por los Partidos Morena y del Trabajo, así como dichos Partidos'),
(986,'Consejo Distrital 12 del Instituto Electoral de la Ciudad de México.'),
(987,'Comisión Sociocultural y Deportiva del Pueblo Originario de San Pedro Mártir, Demarcación Tlalpan'),
(988,'Junta Cívica de Santa Úrsula Xitla y Alcaldía Tlalpan'),
(989,'Comité Ejecutivo Nacional, Comisión Nacional de Honestidad y Justicia, y Comisión Coadyuvante, todos de MORENA'),
(990,'Comisión Sociocultural y Deportiva del Pueblo de San Pedro Mártir 2019-2020'),
(991,'Comisión Permanente de Igualdad de Género y Derechos Humanos del Instituto Electoral de la Ciudad de México'),
(992,'José Carlos Acosta Ruiz, Alcalde y otrora candidato a la Alcaldía Xochimilco y otras personas'),
(993,'Partido Verde Ecologista de México y otras personas'),
(994,'Medio Digital “Demos Tracking, Polls.mx y Político.mx”'),
(995,'Francisco Chíguil Figueroa, en su cálidas de persona candidata a la Alcaldía Gustavo A. Madero por el Partido Morena'),
(996,'Secretario Administrativo, Titulares de las Unidades Técnicas del Centro de Formación y Desarrollo y Servicios Informáticos, todos del Instituto Electoral de la Ciudad de México'),
(997,'Carlos Alonso Castillo Pérez, otrora persona candidata a la Alcaldía en Coyoacán'),
(998,'Comisión de Participación Comunitaria de la Unidad Territorial Modelo, Iztapalapa.'),
(999,'Secretario Administrativo y Titular de la Unidad Técnica del Centro de Formación y Desarrollo del Instituto Electoral de la Ciudad de México'),
(1000,'Consejo Electoral del Pueblo de San Salvador Cuauhtenco y Alcaldía Milpa Alta'),
(1001,'Presidenta del Comité Pro-Panteón del pueblo de San Gregorio Atlapulco'),
(1002,'Junta Cívica del Pueblo Originario de Chimalcoyoc en Tlalpan'),
(1003,'Consejo General y Secretaría Administrativa ambas del Instituto Electoral de la Ciudad de México'),
(1004,'Personas ex integrantes del Comité Pro-Panteón del pueblo de San Gregorio Atlapulco y la Dirección Distrital 25 del Instituto Electoral de la Ciudad de México'),
(1005,'Autoridad Tradicional del Pueblo de San Bartolo Ameyalco'),
(1006,'Consejo del Pueblo de San Mateo Xalpa, Xochimilco'),
(1007,'Autoridad Tradicional del Pueblo de Santiago Tulyehualco'),
(1008,'Personas integrantes del del pueblo de San Gregorio Atlapulco y Dirección Distrital 25 del IECM'),
(1009,'Alcaldía La Magdalena Contreras'),
(1010,'Comisión de Igualdad de Género y el Pleno del Parlamento de Mujeres 2022 ambas del Congreso de la Ciudad de México'),
(1011,'Vicente Carlos Serrano Arroyo, usuario “Sin Censura, @_VicenteSerrano” de la Red Social Twitter y otros'),
(1012,'Comisión Organizadora del Pueblo Santa Isabel Tola'),
(1013,'Autoridad Tradicional del Pueblo de Cuauhtepec'),
(1014,'Comisión Provisional Encargada de Vigilar la Oportuna Conformación de los Consejos Distritales del IECM'),
(1015,'Consejo General y Secretaría Ejecutiva del IECM'),
(1016,'Secretaría de Gobierno en la Ciudad de México'),
(1017,'Secretaría General'),
(1018,'Comité Directivo del Partido Revolucionario Institucional de la Ciudad de México'),
(1019,'Eduardo Urquiza Isla y otras personas'),
(1020,'Concejo Autónomo de Gobierno del Pueblo de San Luis Tlaxialtemalco'),
(1021,'Secretaría Administrativa del Instituto Electoral de la Ciudad de México y otro'),
(1022,'Luis Alberto Mendoza Acevedo, Diputado Federal por el Distrito 15'),
(1023,'Santiago Taboada Cortina, Titular de la Alcaldía Benito Juárez'),
(1024,'Comisión Organizadora de la Elección de la Coordinadora o Coordinador del Pueblo de San Juan Ixtayopan, Tláhuac');

