SET FOREIGN_KEY_CHECKS=0;
DROP TABLE eel_cat_tipo_documento;
DROP TABLE eel_documentos;
DROP TABLE inst_cat_areas;
DROP TABLE inst_cat_sexo;
DROP TABLE inst_empleados;
DROP TABLE jel_demanda;
DROP TABLE jel_demanda_archivo;
DROP TABLE ssg_cat_areas_turnables;
DROP TABLE ssg_cat_autoridades_responsables;
DROP TABLE ssg_cat_domicilios;
DROP TABLE ssg_cat_tipo_asuntos;
DROP TABLE ssg_cat_tipos_acuerdos;
DROP TABLE ssg_cat_tipos_involucrados;
DROP TABLE ssg_cat_tipos_turnados;
DROP TABLE ssg_cat_tribunal;
DROP TABLE ssg_cat_via_recepcion;
DROP TABLE ssg_cfg_params;
DROP TABLE ssg_medio_impugnacion;
DROP TABLE ssg_medios_autoridades;
DROP TABLE ssg_rel_medio_impugnacion_involucrados;
DROP TABLE ssg_rel_medios_acuerdos;
DROP TABLE ssg_rel_medios_turnados;
SET FOREIGN_KEY_CHECKS=1;